query DocumentScreen_Query($entityId: ID!) {
  entity(entityId: $entityId) @catch(to: THROW) {
    id
    depth
    url
    visibility
    availability
    ...EntityIcon_entity
    ...EntityBreadcrumb_entity

    goal {
      ...EntityGoalFields_goal
    }

    ancestors {
      id

      goal {
        ...EntityGoalFields_goal
      }

      node {
        __typename

        ... on Folder {
          id
          characterCount
        }
      }
    }

    node {
      __typename

      ... on Document {
        id
        title
        subtitle
        type
        layoutMode
        locked
        createdAt
        updatedAt
        characterCount
        characterCountChange {
          additions
          deletions
        }
      }
    }
  }
}

mutation DocumentScreen_UpdateDocumentLock_Mutation($input: UpdateDocumentInput!) {
  updateDocument(input: $input) {
    id
    locked
  }
}
