pub(crate) mod common;
pub(crate) mod composition;
pub(crate) mod cursor;
pub(crate) mod dnd;
pub(crate) mod grapheme;
pub(crate) mod hit_test;
pub(crate) mod interactive;
pub(crate) mod link;
pub(crate) mod navigation;
pub(crate) mod pointer_style;
pub(crate) mod search;
pub(crate) mod segmentation;
pub(crate) mod selection;
pub(crate) mod selection_drag;
mod visit;

pub use composition::CompositionRect;
pub use cursor::CursorMetrics;
pub(crate) use cursor::cursor_metrics;
pub(crate) use dnd::drop_target_at;
pub(crate) use hit_test::HitTester;
pub use interactive::InteractiveHit;
pub(crate) use interactive::interactive_hit_test;
pub use link::LinkRect;
pub(crate) use link::{link_hit_test, page_link_rects};
pub(crate) use navigation::resolve_movement;
pub use pointer_style::PointerStyle;
pub(crate) use pointer_style::pointer_style_at;
pub use selection::{SelectionEndpoints, SelectionRect, SelectionRectKind};
pub use visit::{Edges, LineMetrics, PageVisitor, visit_page};
