-- Step B: create one placeholder UserDevices row per existing UserSessions row,
-- then point user_sessions.device_id at it. The NOT NULL + unique tightening
-- is applied by the next migration (auto-generated by drizzle-kit).

INSERT INTO "user_devices" ("id", "user_id", "identifier", "name", "platform", "last_active_at", "last_active_ip", "created_at")
SELECT
  'UDEV0' || upper(substr(md5(random()::text || clock_timestamp()::text || s."id"), 1, 14)),
  s."user_id",
  'legacy:' || s."id",
  '알 수 없는 기기',
  'WEB',
  s."created_at",
  NULL,
  s."created_at"
FROM "user_sessions" s;

UPDATE "user_sessions" s
SET "device_id" = d."id"
FROM "user_devices" d
WHERE d."identifier" = 'legacy:' || s."id";
