packages:
  - apps/*
  - crates/*
  - packages/*
  - legacy/*
  - assets
allowBuilds:
  '@firebase/util': false
  '@sentry/cli': false
  argon2: true
  es5-ext: false
  esbuild: true
  msgpackr-extract: false
  protobufjs: false
  sharp: true
  ttf2woff2: true
  unrs-resolver: false
  wasm-pack: false
