productName = "Typie"
version = "0.0.1"
identifier = "co.typie"

[build]
beforeDevCommand = "pnpm vite dev"
beforeBuildCommand = "pnpm vite build"
devUrl = "http://localhost:5100"
frontendDist = "../build"

[[app.windows]]
title = "타이피"
hiddenTitle = true
titleBarStyle = "Overlay"
trafficLightPosition = { x = 16, y = 16 }

[bundle]
active = true
targets = ["nsis", "dmg"]
icon = ["icons/icon.icns"]
resources = { "resources/" = "./" }

[bundle.macOS.dmg]
background = "assets/dmg-background.png"
windowSize = { width = 660, height = 400 }

[plugins.deep-link.desktop]
schemes = ["typie"]
