productName = "Typie"
version = "0.0.4"
identifier = "co.typie"

[build]
beforeDevCommand = "pnpm vite dev"
beforeBuildCommand = "pnpm vite build"
devUrl = "http://localhost:5100"
frontendDist = "../build"

[[app.windows]]
width = 1280
height = 720
title = "타이피"
hiddenTitle = true
titleBarStyle = "Overlay"
trafficLightPosition = { x = 16, y = 16 }

[bundle]
active = true
targets = ["nsis", "dmg", "app"]
icon = ["icons/icon.icns", "icons/icon.ico"]
resources = { "resources/" = "./" }
createUpdaterArtifacts = true

[bundle.macOS.dmg]
background = "assets/dmg-background.png"
windowSize = { width = 660, height = 400 }

[plugins.deep-link.desktop]
schemes = ["typie"]

[plugins.updater]
pubkey = "dW50cnVzdGVkIGNvbW1lbnQ6IG1pbmlzaWduIHB1YmxpYyBrZXk6IEEzMUE1NThDRUQ3MjdFNkQKUldSdGZuTHRqRlVhb3poU3dNUjZzWU9vMnRRaUkrR3FoeGNlaDdIRVJ3MGcrWkFPLy9KY1BmUHYK"
endpoints = ["https://app.typie.net/updates/version.json"]
