use std::collections::HashMap;
use std::fmt::Write as _;
use std::path::Path;

use heck::ToLowerCamelCase;

use crate::meta::{FfiField, FfiKind, FfiMeta, FfiVariant};

const HEADER: &str =
    "// This file is auto-generated by editor-bindgen. Do not edit.\n\nimport Foundation\n\n";

const SUPPORT: &str = r#"public struct FFIKey: CodingKey, ExpressibleByStringLiteral, Sendable {
  public let stringValue: String
  public var intValue: Int? { nil }

  public init(stringValue: String) {
    self.stringValue = stringValue
  }

  public init?(intValue: Int) {
    nil
  }

  public init(stringLiteral value: String) {
    self.stringValue = value
  }
}

public struct FFIUnit: Codable, Hashable, Sendable {
  public init() {}

  public init(from decoder: any Decoder) throws {
    let container = try decoder.singleValueContainer()
    guard container.decodeNil() else {
      throw DecodingError.dataCorruptedError(in: container, debugDescription: "expected null")
    }
  }

  public func encode(to encoder: any Encoder) throws {
    var container = encoder.singleValueContainer()
    try container.encodeNil()
  }
}
"#;

const SWIFT_KEYWORDS: &[&str] = &[
    "Any",
    "Self",
    "Type",
    "as",
    "associatedtype",
    "await",
    "borrowing",
    "break",
    "case",
    "catch",
    "class",
    "consuming",
    "continue",
    "default",
    "defer",
    "deinit",
    "do",
    "else",
    "enum",
    "extension",
    "fallthrough",
    "false",
    "fileprivate",
    "for",
    "func",
    "guard",
    "if",
    "import",
    "in",
    "init",
    "inout",
    "internal",
    "is",
    "let",
    "nil",
    "nonisolated",
    "open",
    "operator",
    "private",
    "precedencegroup",
    "protocol",
    "public",
    "repeat",
    "rethrows",
    "return",
    "self",
    "static",
    "struct",
    "subscript",
    "super",
    "switch",
    "throw",
    "throws",
    "true",
    "try",
    "typealias",
    "var",
    "where",
    "while",
];

pub fn generate_all(metas: &[FfiMeta], output_dir: &Path) {
    std::fs::create_dir_all(output_dir).expect("failed to create output directory");
    let ctx = Context::new(metas);
    std::fs::write(
        output_dir.join("FFISupport.swift"),
        format!("{HEADER}{SUPPORT}"),
    )
    .expect("failed to write FFISupport.swift");
    for meta in metas {
        if let Some(body) = generate(meta, &ctx) {
            std::fs::write(
                output_dir.join(format!("{}.swift", meta.name)),
                format!("{HEADER}{body}"),
            )
            .expect("failed to write file");
        }
    }
}

enum Tagging<'a> {
    Internal { tag: &'a str },
    Adjacent { tag: &'a str, content: &'a str },
    External,
}

struct Context<'a> {
    custom_types: HashMap<&'a str, &'a str>,
    metas: HashMap<&'a str, &'a FfiMeta>,
}

impl<'a> Context<'a> {
    fn new(metas: &'a [FfiMeta]) -> Self {
        let mut custom_types = HashMap::new();
        let mut by_name = HashMap::new();
        for meta in metas {
            if let FfiKind::Custom { target } = &meta.kind {
                custom_types.insert(meta.name.as_str(), target.as_str());
            }
            assert!(
                by_name.insert(meta.name.as_str(), meta).is_none(),
                "duplicate FFI type name `{}`",
                meta.name
            );
        }
        Self {
            custom_types,
            metas: by_name,
        }
    }

    fn swift_type(&self, rust_ty: &str, generics: &[String], site: &str) -> String {
        let parsed: syn::Type = syn::parse_str(rust_ty)
            .unwrap_or_else(|error| panic!("{site}: failed to parse type `{rust_ty}`: {error}"));
        self.map_type(&parsed, generics, site)
    }

    fn map_type(&self, ty: &syn::Type, generics: &[String], site: &str) -> String {
        match ty {
            syn::Type::Tuple(tuple) if tuple.elems.is_empty() => "FFIUnit".into(),
            syn::Type::Path(path) => self.map_path(path, generics, site),
            _ => panic!(
                "{site}: unsupported type in FFI metadata: {}",
                quote::quote!(#ty)
            ),
        }
    }

    fn map_path(&self, type_path: &syn::TypePath, generics: &[String], site: &str) -> String {
        let segments: Vec<_> = type_path.path.segments.iter().collect();
        let last = segments.last().expect("empty path");
        let ident = last.ident.to_string();
        let full = segments
            .iter()
            .map(|segment| segment.ident.to_string())
            .collect::<Vec<_>>()
            .join("::");
        let args: Vec<&syn::Type> = match &last.arguments {
            syn::PathArguments::None => Vec::new(),
            syn::PathArguments::AngleBracketed(args) => args
                .args
                .iter()
                .filter_map(|arg| match arg {
                    syn::GenericArgument::Type(ty) => Some(ty),
                    _ => None,
                })
                .collect(),
            syn::PathArguments::Parenthesized(_) => {
                panic!("{site}: unsupported path arguments: {full}")
            }
        };
        if args.is_empty() {
            if segments.len() == 1
                && let Some(target) = self.custom_types.get(ident.as_str())
            {
                return self.swift_type(target, &[], site);
            }
            if let Some(primitive) = primitive(&ident) {
                return primitive.into();
            }
            return self.known_type(ident, &full, generics, site);
        }
        match full.as_str() {
            "Option" => format!("{}?", self.map_type(args[0], generics, site)),
            "Vec" | "imbl::Vector" | "VecDeque" | "std::collections::VecDeque" => {
                format!("[{}]", self.map_type(args[0], generics, site))
            }
            "SmallVec" | "smallvec::SmallVec" => {
                let syn::Type::Array(array) = args[0] else {
                    panic!("{site}: SmallVec expects an array type argument");
                };
                format!("[{}]", self.map_type(&array.elem, generics, site))
            }
            "Box" | "Arc" | "std::sync::Arc" | "Rc" | "std::rc::Rc" => {
                self.map_type(args[0], generics, site)
            }
            "HashMap"
            | "imbl::HashMap"
            | "imbl::OrdMap"
            | "std::collections::HashMap"
            | "hashbrown::HashMap"
            | "BTreeMap"
            | "std::collections::BTreeMap" => {
                let key_ty = args[0];
                let key = self.map_type(key_ty, generics, site);
                assert!(
                    self.is_object_key(&key),
                    "{site}: unsupported dictionary key type `{}` (Swift `{key}`): JSONEncoder writes only String, Int, and String-backed CodingKeyRepresentable enum keys as object keys",
                    quote::quote!(#key_ty)
                );
                format!("[{key}: {}]", self.map_type(args[1], generics, site))
            }
            "HashSet"
            | "imbl::HashSet"
            | "imbl::OrdSet"
            | "std::collections::HashSet"
            | "hashbrown::HashSet"
            | "BTreeSet"
            | "std::collections::BTreeSet" => {
                format!("Set<{}>", self.map_type(args[0], generics, site))
            }
            _ => format!(
                "{}<{}>",
                self.known_type(ident, &full, generics, site),
                args.iter()
                    .map(|arg| self.map_type(arg, generics, site))
                    .collect::<Vec<_>>()
                    .join(", ")
            ),
        }
    }

    fn known_type(&self, ident: String, full: &str, generics: &[String], site: &str) -> String {
        assert!(
            self.metas.contains_key(ident.as_str()) || generics.contains(&ident),
            "{site}: unknown type `{full}` in FFI metadata: not a primitive, an #[ffi] type, or a generic parameter of the type being generated"
        );
        ident
    }

    fn is_object_key(&self, swift_ty: &str) -> bool {
        matches!(swift_ty, "String" | "Int")
            || matches!(
                self.metas.get(swift_ty).map(|meta| &meta.kind),
                Some(FfiKind::Enum { variants, serde_tag, .. })
                    if is_string_enum(variants, serde_tag.as_deref())
            )
    }

    fn default_value(&self, field: &FfiField, swift_ty: &str, site: &str) -> String {
        if let Some(value) = &field.ffi_default_override {
            return value.clone();
        }
        if swift_ty.ends_with('?') {
            return "nil".into();
        }
        if swift_ty.starts_with('[') {
            return if is_dictionary(swift_ty) {
                "[:]".into()
            } else {
                "[]".into()
            };
        }
        if swift_ty.starts_with("Set<") {
            return "[]".into();
        }
        let head = swift_ty.split('<').next().unwrap_or(swift_ty);
        if let Some(meta) = self.metas.get(head) {
            match &meta.kind {
                FfiKind::Enum {
                    default_variant: Some(variant),
                    ..
                } => return format!(".{}", case_name(variant)),
                FfiKind::Struct { fields } if fields.iter().all(|f| f.has_serde_default) => {
                    return format!("{swift_ty}()");
                }
                FfiKind::Struct { .. } => panic!(
                    "{site}: no Swift default for `{swift_ty}`: every field of `{head}` needs #[serde(default)], or this field needs #[ffi(default = \"...\")]"
                ),
                _ => {}
            }
        }
        match swift_ty {
            "Bool" => "false".into(),
            "String" => "\"\"".into(),
            "UInt8" | "UInt16" | "UInt32" | "UInt64" | "Int8" | "Int16" | "Int32" | "Int64"
            | "Int" | "Float" | "Double" => "0".into(),
            _ => format!("{swift_ty}()"),
        }
    }

    fn is_uninhabited(&self, swift_ty: &str) -> bool {
        matches!(
            self.metas.get(swift_ty).map(|meta| &meta.kind),
            Some(FfiKind::Enum { variants, .. }) if variants.is_empty()
        )
    }

    fn member(
        &self,
        field: &FfiField,
        rule: RenameRule,
        generics: &[String],
        owner: &str,
    ) -> Member {
        let site = format!("{owner}.{}", field.name);
        let ty = self.swift_type(&field.ty, generics, &site);
        let default = field
            .has_serde_default
            .then(|| self.default_value(field, &ty, &site));
        Member {
            ident: identifier(&field.name.to_lower_camel_case()),
            key: field
                .serde_rename
                .clone()
                .unwrap_or_else(|| rule.apply_to_field(&field.name)),
            ty,
            default,
        }
    }
}

struct Member {
    ident: String,
    key: String,
    ty: String,
    default: Option<String>,
}

impl Member {
    fn declaration(&self) -> String {
        match &self.default {
            Some(value) => format!("{}: {} = {}", self.ident, self.ty, value),
            None => format!("{}: {}", self.ident, self.ty),
        }
    }

    fn decode(&self, container: &str) -> String {
        if let Some(inner) = self.ty.strip_suffix('?') {
            let base = format!(
                "{container}.decodeIfPresent({inner}.self, forKey: \"{}\")",
                self.key
            );
            return match self.default.as_deref() {
                Some(value) if value != "nil" => format!("{base} ?? {value}"),
                _ => base,
            };
        }
        match &self.default {
            Some(value) => format!(
                "{container}.decodeIfPresent({}.self, forKey: \"{}\") ?? {value}",
                self.ty, self.key
            ),
            None => format!(
                "{container}.decode({}.self, forKey: \"{}\")",
                self.ty, self.key
            ),
        }
    }
}

enum Shape {
    Unit,
    Fields(Vec<Member>),
    Flatten(String),
    Newtype(String),
}

struct Case {
    name: String,
    key: String,
    shape: Shape,
    uninhabited: Option<String>,
}

impl Case {
    fn uninhabited_throw(&self, key: &str) -> Option<String> {
        self.uninhabited
            .as_ref()
            .map(|ty| throw_corrupted(key, &format!("{ty} has no variants")))
    }

    fn declaration(&self) -> String {
        match &self.shape {
            Shape::Unit => format!("case {}", self.name),
            Shape::Fields(members) if members.is_empty() => format!("case {}", self.name),
            Shape::Fields(members) => format!(
                "case {}({})",
                self.name,
                members
                    .iter()
                    .map(Member::declaration)
                    .collect::<Vec<_>>()
                    .join(", ")
            ),
            Shape::Flatten(ty) | Shape::Newtype(ty) => format!("case {}({ty})", self.name),
        }
    }

    fn pattern(&self) -> String {
        match &self.shape {
            Shape::Unit => format!(".{}", self.name),
            Shape::Fields(members) if members.is_empty() => format!(".{}", self.name),
            Shape::Fields(members) => format!(
                ".{}({})",
                self.name,
                members
                    .iter()
                    .map(|member| format!("let {}", member.ident))
                    .collect::<Vec<_>>()
                    .join(", ")
            ),
            Shape::Flatten(_) | Shape::Newtype(_) => format!(".{}(let payload)", self.name),
        }
    }

    fn construct(&self, container: &str) -> String {
        match &self.shape {
            Shape::Unit => format!(".{}", self.name),
            Shape::Fields(members) if members.is_empty() => format!(".{}", self.name),
            Shape::Fields(members) => format!(
                "try .{}({})",
                self.name,
                members
                    .iter()
                    .map(|member| format!(
                        "{}: {}",
                        member.ident.trim_matches('`'),
                        member.decode(container)
                    ))
                    .collect::<Vec<_>>()
                    .join(", ")
            ),
            Shape::Flatten(ty) => format!("try .{}({ty}(from: decoder))", self.name),
            Shape::Newtype(_) => unreachable!("newtype payloads are decoded per tagging"),
        }
    }

    fn payload_types(&self) -> Vec<&str> {
        match &self.shape {
            Shape::Unit => Vec::new(),
            Shape::Fields(members) => members.iter().map(|member| member.ty.as_str()).collect(),
            Shape::Flatten(ty) | Shape::Newtype(ty) => vec![ty.as_str()],
        }
    }
}

fn generate(meta: &FfiMeta, ctx: &Context) -> Option<String> {
    match &meta.kind {
        FfiKind::Custom { .. } => None,
        FfiKind::Struct { fields } => Some(generate_struct(meta, fields, ctx)),
        FfiKind::Enum {
            variants,
            serde_tag,
            serde_content,
            ..
        } => {
            if is_string_enum(variants, serde_tag.as_deref()) {
                return Some(generate_raw_enum(meta, variants));
            }
            let tagging = match (serde_tag.as_deref(), serde_content.as_deref()) {
                (Some(tag), None) => Tagging::Internal { tag },
                (Some(tag), Some(content)) => Tagging::Adjacent { tag, content },
                (None, _) => Tagging::External,
            };
            Some(generate_tagged_enum(meta, variants, &tagging, ctx))
        }
    }
}

fn declared_name(meta: &FfiMeta) -> String {
    if meta.generics.is_empty() {
        meta.name.clone()
    } else {
        format!(
            "{}<{}>",
            meta.name,
            meta.generics
                .iter()
                .map(|param| format!("{param}: Codable & Hashable & Sendable"))
                .collect::<Vec<_>>()
                .join(", ")
        )
    }
}

fn generate_struct(meta: &FfiMeta, fields: &[FfiField], ctx: &Context) -> String {
    let rule = RenameRule::parse(meta.serde_rename_all.as_deref(), &meta.name);
    let members: Vec<Member> = fields
        .iter()
        .map(|field| ctx.member(field, rule, &meta.generics, &meta.name))
        .collect();
    let mut out = String::new();
    writeln!(
        out,
        "public struct {}: Codable, Hashable, Sendable {{",
        declared_name(meta)
    )
    .unwrap();
    for member in &members {
        writeln!(out, "  public var {}: {}", member.ident, member.ty).unwrap();
    }
    if !members.is_empty() {
        out.push('\n');
    }
    writeln!(
        out,
        "  public init({}) {{",
        members
            .iter()
            .map(Member::declaration)
            .collect::<Vec<_>>()
            .join(", ")
    )
    .unwrap();
    for member in &members {
        writeln!(out, "    self.{} = {}", member.ident, member.ident).unwrap();
    }
    out.push_str("  }\n\n");
    out.push_str("  public init(from decoder: any Decoder) throws {\n");
    if members.is_empty() {
        out.push_str("    _ = try decoder.container(keyedBy: FFIKey.self)\n");
    } else {
        out.push_str("    let container = try decoder.container(keyedBy: FFIKey.self)\n");
        for member in &members {
            writeln!(
                out,
                "    {} = try {}",
                member.ident,
                member.decode("container")
            )
            .unwrap();
        }
    }
    out.push_str("  }\n\n");
    out.push_str("  public func encode(to encoder: any Encoder) throws {\n");
    if members.is_empty() {
        out.push_str("    _ = encoder.container(keyedBy: FFIKey.self)\n");
    } else {
        out.push_str("    var container = encoder.container(keyedBy: FFIKey.self)\n");
        for member in &members {
            writeln!(
                out,
                "    try container.encode({}, forKey: \"{}\")",
                member.ident, member.key
            )
            .unwrap();
        }
    }
    out.push_str("  }\n}\n");
    out
}

fn generate_raw_enum(meta: &FfiMeta, variants: &[FfiVariant]) -> String {
    let rule = RenameRule::parse(meta.serde_rename_all.as_deref(), &meta.name);
    let mut out = String::new();
    writeln!(
        out,
        "public enum {}: String, Codable, Hashable, Sendable, CodingKeyRepresentable {{",
        meta.name
    )
    .unwrap();
    for variant in variants {
        let FfiVariant::Unit { name } = variant else {
            unreachable!()
        };
        writeln!(
            out,
            "  case {} = \"{}\"",
            case_name(name),
            rule.apply_to_variant(name)
        )
        .unwrap();
    }
    out.push_str("}\n");
    out
}

fn build_cases(
    meta: &FfiMeta,
    variants: &[FfiVariant],
    tagging: &Tagging,
    ctx: &Context,
) -> Vec<Case> {
    let rule = RenameRule::parse(meta.serde_rename_all.as_deref(), &meta.name);
    variants
        .iter()
        .map(|variant| {
            let (name, shape) = match variant {
                FfiVariant::Unit { name } => (name, Shape::Unit),
                FfiVariant::Struct {
                    name,
                    fields,
                    serde_rename_all,
                } => {
                    let owner = format!("{}::{name}", meta.name);
                    let field_rule = RenameRule::parse(serde_rename_all.as_deref(), &owner);
                    (
                        name,
                        Shape::Fields(
                            fields
                                .iter()
                                .map(|field| ctx.member(field, field_rule, &meta.generics, &owner))
                                .collect(),
                        ),
                    )
                }
                FfiVariant::Tuple { name, tys } => {
                    assert!(
                        tys.len() == 1,
                        "{}::{name}: tuple variants with {} fields are not supported",
                        meta.name,
                        tys.len()
                    );
                    let site = format!("{}::{name}", meta.name);
                    let shape = match tagging {
                        Tagging::Internal { .. } => match ctx.metas.get(tys[0].as_str()).map(|m| &m.kind) {
                            Some(FfiKind::Struct { fields }) if fields.is_empty() => Shape::Unit,
                            Some(FfiKind::Struct { .. }) => Shape::Flatten(ctx.swift_type(&tys[0], &meta.generics, &site)),
                            _ => panic!(
                                "{}::{name}: internally tagged newtype variants must wrap a struct, found `{}`",
                                meta.name, tys[0]
                            ),
                        },
                        Tagging::Adjacent { .. } | Tagging::External => {
                            Shape::Newtype(ctx.swift_type(&tys[0], &meta.generics, &site))
                        }
                    };
                    (name, shape)
                }
            };
            let case = Case {
                name: case_name(name),
                key: rule.apply_to_variant(name),
                shape,
                uninhabited: None,
            };
            let uninhabited = case
                .payload_types()
                .into_iter()
                .find(|ty| ctx.is_uninhabited(ty))
                .map(str::to_string);
            Case {
                uninhabited,
                ..case
            }
        })
        .collect()
}

fn generate_tagged_enum(
    meta: &FfiMeta,
    variants: &[FfiVariant],
    tagging: &Tagging,
    ctx: &Context,
) -> String {
    let cases = build_cases(meta, variants, tagging, ctx);
    let recursive = cases
        .iter()
        .flat_map(Case::payload_types)
        .any(|ty| mentions(ty, &meta.name));
    let mut out = String::new();
    writeln!(
        out,
        "public {}enum {}: Codable, Hashable, Sendable {{",
        if recursive { "indirect " } else { "" },
        declared_name(meta)
    )
    .unwrap();
    for case in &cases {
        writeln!(out, "  {}", case.declaration()).unwrap();
    }
    if !cases.is_empty() {
        out.push('\n');
    }
    if cases.is_empty() {
        writeln!(
            out,
            "  public init(from decoder: any Decoder) throws {{\n    throw DecodingError.dataCorrupted(\n      .init(codingPath: decoder.codingPath, debugDescription: \"{} has no variants\"))\n  }}\n\n  public func encode(to encoder: any Encoder) throws {{}}\n}}",
            meta.name
        )
        .unwrap();
        return out;
    }
    match tagging {
        Tagging::Internal { tag } => write_internal(&mut out, &cases, tag),
        Tagging::Adjacent { tag, content } => write_adjacent(&mut out, &cases, tag, content),
        Tagging::External => write_external(&mut out, &cases),
    }
    out.push_str("}\n");
    out
}

fn throw_corrupted(key: &str, description: &str) -> String {
    format!(
        "      throw DecodingError.dataCorruptedError(\n        forKey: {key}, in: container, debugDescription: \"{description}\")\n"
    )
}

fn unknown_variant(key: &str) -> String {
    throw_corrupted(&format!("\"{key}\""), "unknown variant \\(tag)")
}

fn write_internal(out: &mut String, cases: &[Case], tag: &str) {
    out.push_str("  public init(from decoder: any Decoder) throws {\n");
    out.push_str("    let container = try decoder.container(keyedBy: FFIKey.self)\n");
    writeln!(
        out,
        "    let tag = try container.decode(String.self, forKey: \"{tag}\")"
    )
    .unwrap();
    out.push_str("    switch tag {\n");
    for case in cases {
        writeln!(out, "    case \"{}\":", case.key).unwrap();
        match case.uninhabited_throw(&format!("\"{tag}\"")) {
            Some(throw) => out.push_str(&throw),
            None => writeln!(out, "      self = {}", case.construct("container")).unwrap(),
        }
    }
    out.push_str("    default:\n");
    out.push_str(&unknown_variant(tag));
    out.push_str("    }\n  }\n\n");
    out.push_str("  public func encode(to encoder: any Encoder) throws {\n    switch self {\n");
    for case in cases {
        writeln!(out, "    case {}:", case.pattern()).unwrap();
        if let Shape::Flatten(_) = case.shape {
            out.push_str("      try payload.encode(to: encoder)\n");
        }
        out.push_str("      var container = encoder.container(keyedBy: FFIKey.self)\n");
        writeln!(
            out,
            "      try container.encode(\"{}\", forKey: \"{tag}\")",
            case.key
        )
        .unwrap();
        if let Shape::Fields(members) = &case.shape {
            for member in members {
                writeln!(
                    out,
                    "      try container.encode({}, forKey: \"{}\")",
                    member.ident, member.key
                )
                .unwrap();
            }
        }
    }
    out.push_str("    }\n  }\n");
}

fn write_adjacent(out: &mut String, cases: &[Case], tag: &str, content: &str) {
    out.push_str("  public init(from decoder: any Decoder) throws {\n");
    out.push_str("    let container = try decoder.container(keyedBy: FFIKey.self)\n");
    writeln!(
        out,
        "    let tag = try container.decode(String.self, forKey: \"{tag}\")"
    )
    .unwrap();
    out.push_str("    switch tag {\n");
    for case in cases {
        writeln!(out, "    case \"{}\":", case.key).unwrap();
        if let Some(throw) = case.uninhabited_throw(&format!("\"{tag}\"")) {
            out.push_str(&throw);
            continue;
        }
        match &case.shape {
            Shape::Newtype(ty) => writeln!(
                out,
                "      self = try .{}(container.decode({ty}.self, forKey: \"{content}\"))",
                case.name
            )
            .unwrap(),
            Shape::Fields(members) if !members.is_empty() => {
                writeln!(
                    out,
                    "      let content = try container.nestedContainer(keyedBy: FFIKey.self, forKey: \"{content}\")"
                )
                .unwrap();
                writeln!(out, "      self = {}", case.construct("content")).unwrap();
            }
            _ => writeln!(out, "      self = .{}", case.name).unwrap(),
        }
    }
    out.push_str("    default:\n");
    out.push_str(&unknown_variant(tag));
    out.push_str("    }\n  }\n\n");
    out.push_str("  public func encode(to encoder: any Encoder) throws {\n");
    out.push_str("    var container = encoder.container(keyedBy: FFIKey.self)\n");
    out.push_str("    switch self {\n");
    for case in cases {
        writeln!(out, "    case {}:", case.pattern()).unwrap();
        writeln!(
            out,
            "      try container.encode(\"{}\", forKey: \"{tag}\")",
            case.key
        )
        .unwrap();
        match &case.shape {
            Shape::Newtype(_) => writeln!(
                out,
                "      try container.encode(payload, forKey: \"{content}\")"
            )
            .unwrap(),
            Shape::Fields(members) if members.is_empty() => writeln!(
                out,
                "      _ = container.nestedContainer(keyedBy: FFIKey.self, forKey: \"{content}\")"
            )
            .unwrap(),
            Shape::Fields(members) => {
                writeln!(
                    out,
                    "      var content = container.nestedContainer(keyedBy: FFIKey.self, forKey: \"{content}\")"
                )
                .unwrap();
                for member in members {
                    writeln!(
                        out,
                        "      try content.encode({}, forKey: \"{}\")",
                        member.ident, member.key
                    )
                    .unwrap();
                }
            }
            _ => {}
        }
    }
    out.push_str("    }\n  }\n");
}

fn write_external(out: &mut String, cases: &[Case]) {
    let units: Vec<&Case> = cases
        .iter()
        .filter(|case| matches!(case.shape, Shape::Unit))
        .collect();
    out.push_str("  public init(from decoder: any Decoder) throws {\n");
    if !units.is_empty() {
        out.push_str(
            "    if let single = try? decoder.singleValueContainer(), let name = try? single.decode(String.self) {\n      switch name {\n",
        );
        for case in &units {
            writeln!(
                out,
                "      case \"{}\":\n        self = .{}",
                case.key, case.name
            )
            .unwrap();
        }
        out.push_str("      default:\n        throw DecodingError.dataCorruptedError(\n          in: single, debugDescription: \"unknown variant \\(name)\")\n      }\n      return\n    }\n");
    }
    out.push_str("    let container = try decoder.container(keyedBy: FFIKey.self)\n");
    out.push_str("    guard container.allKeys.count == 1, let key = container.allKeys.first else {\n      throw DecodingError.dataCorrupted(\n        .init(codingPath: decoder.codingPath, debugDescription: \"expected a single-key object\"))\n    }\n");
    out.push_str("    switch key.stringValue {\n");
    for case in cases
        .iter()
        .filter(|case| !matches!(case.shape, Shape::Unit))
    {
        writeln!(out, "    case \"{}\":", case.key).unwrap();
        if let Some(throw) = case.uninhabited_throw("key") {
            out.push_str(&throw);
            continue;
        }
        match &case.shape {
            Shape::Newtype(ty) => writeln!(
                out,
                "      self = try .{}(container.decode({ty}.self, forKey: key))",
                case.name
            )
            .unwrap(),
            Shape::Fields(members) if members.is_empty() => {
                writeln!(out, "      self = .{}", case.name).unwrap()
            }
            _ => {
                out.push_str(
                    "      let content = try container.nestedContainer(keyedBy: FFIKey.self, forKey: key)\n",
                );
                writeln!(out, "      self = {}", case.construct("content")).unwrap();
            }
        }
    }
    out.push_str("    default:\n      throw DecodingError.dataCorruptedError(\n        forKey: key, in: container, debugDescription: \"unknown variant \\(key.stringValue)\")\n    }\n  }\n\n");
    out.push_str("  public func encode(to encoder: any Encoder) throws {\n    switch self {\n");
    for case in cases {
        writeln!(out, "    case {}:", case.pattern()).unwrap();
        match &case.shape {
            Shape::Unit => writeln!(
                out,
                "      var single = encoder.singleValueContainer()\n      try single.encode(\"{}\")",
                case.key
            )
            .unwrap(),
            Shape::Newtype(_) => writeln!(
                out,
                "      var container = encoder.container(keyedBy: FFIKey.self)\n      try container.encode(payload, forKey: \"{}\")",
                case.key
            )
            .unwrap(),
            Shape::Fields(members) => {
                out.push_str("      var container = encoder.container(keyedBy: FFIKey.self)\n");
                if members.is_empty() {
                    writeln!(
                        out,
                        "      _ = container.nestedContainer(keyedBy: FFIKey.self, forKey: \"{}\")",
                        case.key
                    )
                    .unwrap();
                } else {
                    writeln!(
                        out,
                        "      var content = container.nestedContainer(keyedBy: FFIKey.self, forKey: \"{}\")",
                        case.key
                    )
                    .unwrap();
                    for member in members {
                        writeln!(
                            out,
                            "      try content.encode({}, forKey: \"{}\")",
                            member.ident, member.key
                        )
                        .unwrap();
                    }
                }
            }
            Shape::Flatten(_) => unreachable!("flatten only occurs with internal tagging"),
        }
    }
    out.push_str("    }\n  }\n");
}

fn primitive(ident: &str) -> Option<&'static str> {
    Some(match ident {
        "bool" => "Bool",
        "u8" => "UInt8",
        "u16" => "UInt16",
        "u32" => "UInt32",
        "u64" => "UInt64",
        "i8" => "Int8",
        "i16" => "Int16",
        "i32" => "Int32",
        "i64" => "Int64",
        "usize" | "isize" => "Int",
        "f32" => "Float",
        "f64" => "Double",
        "String" | "char" => "String",
        _ => return None,
    })
}

fn is_string_enum(variants: &[FfiVariant], serde_tag: Option<&str>) -> bool {
    serde_tag.is_none()
        && !variants.is_empty()
        && variants
            .iter()
            .all(|variant| matches!(variant, FfiVariant::Unit { .. }))
}

fn is_dictionary(swift_ty: &str) -> bool {
    let mut depth = 0usize;
    for ch in swift_ty.chars() {
        match ch {
            '[' | '<' => depth += 1,
            ']' | '>' => depth -= 1,
            ':' if depth == 1 => return true,
            _ => {}
        }
    }
    false
}

fn mentions(swift_ty: &str, name: &str) -> bool {
    swift_ty
        .split(|ch: char| !ch.is_alphanumeric() && ch != '_')
        .any(|token| token == name)
}

fn identifier(name: &str) -> String {
    if SWIFT_KEYWORDS.contains(&name) {
        format!("`{name}`")
    } else {
        name.to_string()
    }
}

fn case_name(variant: &str) -> String {
    identifier(&variant.to_lower_camel_case())
}

#[derive(Clone, Copy)]
enum RenameRule {
    None,
    LowerCase,
    UpperCase,
    PascalCase,
    CamelCase,
    SnakeCase,
    ScreamingSnakeCase,
    KebabCase,
    ScreamingKebabCase,
}

impl RenameRule {
    fn parse(rule: Option<&str>, site: &str) -> Self {
        match rule {
            None => Self::None,
            Some("lowercase") => Self::LowerCase,
            Some("UPPERCASE") => Self::UpperCase,
            Some("PascalCase") => Self::PascalCase,
            Some("camelCase") => Self::CamelCase,
            Some("snake_case") => Self::SnakeCase,
            Some("SCREAMING_SNAKE_CASE") => Self::ScreamingSnakeCase,
            Some("kebab-case") => Self::KebabCase,
            Some("SCREAMING-KEBAB-CASE") => Self::ScreamingKebabCase,
            Some(other) => panic!("{site}: unknown serde rename rule `{other}`"),
        }
    }

    fn apply_to_variant(self, variant: &str) -> String {
        match self {
            Self::None | Self::PascalCase => variant.to_owned(),
            Self::LowerCase => variant.to_ascii_lowercase(),
            Self::UpperCase => variant.to_ascii_uppercase(),
            Self::CamelCase => variant[..1].to_ascii_lowercase() + &variant[1..],
            Self::SnakeCase => {
                let mut snake = String::new();
                for (i, ch) in variant.char_indices() {
                    if i > 0 && ch.is_uppercase() {
                        snake.push('_');
                    }
                    snake.push(ch.to_ascii_lowercase());
                }
                snake
            }
            Self::ScreamingSnakeCase => Self::SnakeCase
                .apply_to_variant(variant)
                .to_ascii_uppercase(),
            Self::KebabCase => Self::SnakeCase.apply_to_variant(variant).replace('_', "-"),
            Self::ScreamingKebabCase => Self::ScreamingSnakeCase
                .apply_to_variant(variant)
                .replace('_', "-"),
        }
    }

    fn apply_to_field(self, field: &str) -> String {
        match self {
            Self::None | Self::LowerCase | Self::SnakeCase => field.to_owned(),
            Self::UpperCase => field.to_ascii_uppercase(),
            Self::PascalCase => {
                let mut pascal = String::new();
                let mut capitalize = true;
                for ch in field.chars() {
                    if ch == '_' {
                        capitalize = true;
                    } else if capitalize {
                        pascal.push(ch.to_ascii_uppercase());
                        capitalize = false;
                    } else {
                        pascal.push(ch);
                    }
                }
                pascal
            }
            Self::CamelCase => {
                let pascal = Self::PascalCase.apply_to_field(field);
                pascal[..1].to_ascii_lowercase() + &pascal[1..]
            }
            Self::ScreamingSnakeCase => field.to_ascii_uppercase(),
            Self::KebabCase => field.replace('_', "-"),
            Self::ScreamingKebabCase => Self::ScreamingSnakeCase
                .apply_to_field(field)
                .replace('_', "-"),
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn field(name: &str, ty: &str) -> FfiField {
        FfiField {
            name: name.into(),
            serde_rename: None,
            ty: ty.into(),
            has_serde_default: false,
            ffi_default_override: None,
        }
    }

    fn defaulted(name: &str, ty: &str) -> FfiField {
        FfiField {
            has_serde_default: true,
            ..field(name, ty)
        }
    }

    fn structure(name: &str, rename_all: Option<&str>, fields: Vec<FfiField>) -> FfiMeta {
        FfiMeta {
            name: name.into(),
            kind: FfiKind::Struct { fields },
            serde_rename_all: rename_all.map(Into::into),
            generics: Vec::new(),
        }
    }

    fn enumeration(
        name: &str,
        rename_all: Option<&str>,
        tag: Option<&str>,
        content: Option<&str>,
        variants: Vec<FfiVariant>,
    ) -> FfiMeta {
        FfiMeta {
            name: name.into(),
            kind: FfiKind::Enum {
                variants,
                serde_tag: tag.map(Into::into),
                serde_content: content.map(Into::into),
                default_variant: None,
            },
            serde_rename_all: rename_all.map(Into::into),
            generics: Vec::new(),
        }
    }

    fn unit(name: &str) -> FfiVariant {
        FfiVariant::Unit { name: name.into() }
    }

    fn render(metas: &[FfiMeta], name: &str) -> String {
        let ctx = Context::new(metas);
        let meta = metas.iter().find(|meta| meta.name == name).unwrap();
        generate(meta, &ctx).unwrap()
    }

    fn decode_body(output: &str) -> &str {
        let start = output
            .find("  public init(from decoder: any Decoder) throws {")
            .unwrap();
        let end = output
            .find("  public func encode(to encoder: any Encoder) throws {")
            .unwrap();
        &output[start..end]
    }

    #[test]
    fn maps_rust_types_to_swift_types() {
        let metas = vec![
            FfiMeta {
                name: "Dot".into(),
                kind: FfiKind::Custom {
                    target: "String".into(),
                },
                serde_rename_all: None,
                generics: Vec::new(),
            },
            structure("Size", None, Vec::new()),
            FfiMeta {
                generics: vec!["T".into()],
                ..enumeration("Tri", None, Some("type"), None, vec![unit("Absent")])
            },
        ];
        let ctx = Context::new(&metas);
        let swift = |ty| ctx.swift_type(ty, &[], "Sample.value");
        assert_eq!(swift("u8"), "UInt8");
        assert_eq!(swift("u16"), "UInt16");
        assert_eq!(swift("u32"), "UInt32");
        assert_eq!(swift("u64"), "UInt64");
        assert_eq!(swift("i32"), "Int32");
        assert_eq!(swift("usize"), "Int");
        assert_eq!(swift("f32"), "Float");
        assert_eq!(swift("f64"), "Double");
        assert_eq!(swift("()"), "FFIUnit");
        assert_eq!(swift("Dot"), "String");
        assert_eq!(swift("Option<Vec<Dot>>"), "[String]?");
        assert_eq!(swift("SmallVec<[Dot;1]>"), "[String]");
        assert_eq!(swift("Vec<u8>"), "[UInt8]");
        assert_eq!(swift("BTreeMap<String,Size>"), "[String: Size]");
        assert_eq!(swift("BTreeSet<Size>"), "Set<Size>");
        assert_eq!(swift("Tri<()>"), "Tri<FFIUnit>");
    }

    #[test]
    fn struct_decodes_missing_defaulted_fields_to_defaults() {
        let metas = vec![structure(
            "Position",
            Some("snake_case"),
            vec![
                field("node_id", "String"),
                defaulted("offset", "usize"),
                defaulted("marks", "Vec<String>"),
                defaulted("label", "Option<String>"),
                FfiField {
                    ffi_default_override: Some("100".into()),
                    ..defaulted("proportion", "u32")
                },
            ],
        )];
        let output = render(&metas, "Position");
        assert!(output.contains("public struct Position: Codable, Hashable, Sendable {"));
        assert!(output.contains("  public var nodeId: String\n"));
        assert!(output.contains(
            "  public init(nodeId: String, offset: Int = 0, marks: [String] = [], label: String? = nil, proportion: UInt32 = 100) {"
        ));
        assert!(
            output.contains("    nodeId = try container.decode(String.self, forKey: \"node_id\")")
        );
        assert!(output.contains(
            "    offset = try container.decodeIfPresent(Int.self, forKey: \"offset\") ?? 0"
        ));
        assert!(output.contains(
            "    marks = try container.decodeIfPresent([String].self, forKey: \"marks\") ?? []"
        ));
        assert!(output.contains(
            "    label = try container.decodeIfPresent(String.self, forKey: \"label\")\n"
        ));
        assert!(output.contains(
            "    proportion = try container.decodeIfPresent(UInt32.self, forKey: \"proportion\") ?? 100"
        ));
        assert!(output.contains("    try container.encode(label, forKey: \"label\")"));
    }

    #[test]
    fn struct_default_uses_enum_default_variant() {
        let metas = vec![
            FfiMeta {
                name: "Affinity".into(),
                kind: FfiKind::Enum {
                    variants: vec![unit("Downstream"), unit("Upstream")],
                    serde_tag: None,
                    serde_content: None,
                    default_variant: Some("Upstream".into()),
                },
                serde_rename_all: Some("snake_case".into()),
                generics: Vec::new(),
            },
            structure("Caret", None, vec![defaulted("affinity", "Affinity")]),
        ];
        let output = render(&metas, "Caret");
        assert!(output.contains("public init(affinity: Affinity = .upstream) {"));
    }

    #[test]
    fn empty_struct_round_trips_as_empty_object() {
        let metas = vec![structure(
            "PlainParagraphNode",
            Some("snake_case"),
            Vec::new(),
        )];
        let output = render(&metas, "PlainParagraphNode");
        assert!(output.contains("  public init() {\n  }"));
        assert!(output.contains("    _ = try decoder.container(keyedBy: FFIKey.self)"));
        assert!(output.contains("    _ = encoder.container(keyedBy: FFIKey.self)"));
    }

    #[test]
    fn untagged_unit_enum_is_a_string_enum_usable_as_dictionary_key() {
        let metas = vec![enumeration(
            "FontFamilySource",
            Some("SCREAMING_SNAKE_CASE"),
            None,
            None,
            vec![unit("Default"), unit("User")],
        )];
        let output = render(&metas, "FontFamilySource");
        assert!(output.contains(
            "public enum FontFamilySource: String, Codable, Hashable, Sendable, CodingKeyRepresentable {"
        ));
        assert!(output.contains("  case `default` = \"DEFAULT\""));
        assert!(output.contains("  case user = \"USER\""));
    }

    #[test]
    fn internally_tagged_unit_enum_keeps_the_object_form() {
        let metas = vec![enumeration(
            "CommandRejection",
            Some("snake_case"),
            Some("type"),
            None,
            vec![unit("TargetNotFound")],
        )];
        let output = render(&metas, "CommandRejection");
        assert!(output.contains("public enum CommandRejection: Codable, Hashable, Sendable {"));
        assert!(output.contains("    case \"target_not_found\":\n      self = .targetNotFound"));
        assert!(
            output.contains("      try container.encode(\"target_not_found\", forKey: \"type\")")
        );
    }

    #[test]
    fn internally_tagged_newtype_flattens_the_wrapped_struct() {
        let metas = vec![
            structure(
                "PlainRootNode",
                Some("snake_case"),
                vec![field("layout_mode", "String")],
            ),
            structure("PlainParagraphNode", Some("snake_case"), Vec::new()),
            enumeration(
                "PlainNode",
                Some("snake_case"),
                Some("type"),
                None,
                vec![
                    FfiVariant::Tuple {
                        name: "Root".into(),
                        tys: vec!["PlainRootNode".into()],
                    },
                    FfiVariant::Tuple {
                        name: "Paragraph".into(),
                        tys: vec!["PlainParagraphNode".into()],
                    },
                ],
            ),
        ];
        let output = render(&metas, "PlainNode");
        assert!(output.contains("  case root(PlainRootNode)\n  case paragraph\n"));
        assert!(output.contains("      self = try .root(PlainRootNode(from: decoder))"));
        assert!(output.contains(
            "    case .root(let payload):\n      try payload.encode(to: encoder)\n      var container = encoder.container(keyedBy: FFIKey.self)\n      try container.encode(\"root\", forKey: \"type\")"
        ));
        assert!(output.contains("    case \"paragraph\":\n      self = .paragraph"));
    }

    #[test]
    #[should_panic(expected = "internally tagged newtype variants must wrap a struct")]
    fn internally_tagged_newtype_of_a_primitive_is_rejected() {
        let metas = vec![enumeration(
            "Broken",
            None,
            Some("type"),
            None,
            vec![FfiVariant::Tuple {
                name: "Size".into(),
                tys: vec!["u32".into()],
            }],
        )];
        render(&metas, "Broken");
    }

    #[test]
    fn adjacently_tagged_enum_puts_payloads_under_the_content_key() {
        let metas = vec![enumeration(
            "ImageNodeAttr",
            Some("snake_case"),
            Some("type"),
            Some("value"),
            vec![
                FfiVariant::Tuple {
                    name: "Id".into(),
                    tys: vec!["Option<String>".into()],
                },
                FfiVariant::Struct {
                    name: "Crop".into(),
                    fields: vec![field("top", "u32")],
                    serde_rename_all: None,
                },
                unit("Reset"),
            ],
        )];
        let output = render(&metas, "ImageNodeAttr");
        assert!(
            output.contains(
                "      self = try .id(container.decode(String?.self, forKey: \"value\"))"
            )
        );
        assert!(output.contains(
            "      let content = try container.nestedContainer(keyedBy: FFIKey.self, forKey: \"value\")\n      self = try .crop(top: content.decode(UInt32.self, forKey: \"top\"))"
        ));
        assert!(output.contains("    case \"reset\":\n      self = .reset"));
        assert!(output.contains(
            "    case .id(let payload):\n      try container.encode(\"id\", forKey: \"type\")\n      try container.encode(payload, forKey: \"value\")"
        ));
        assert!(output.contains(
            "      var content = container.nestedContainer(keyedBy: FFIKey.self, forKey: \"value\")\n      try content.encode(top, forKey: \"top\")"
        ));
    }

    #[test]
    fn externally_tagged_enum_uses_the_variant_name_as_key() {
        let metas = vec![enumeration(
            "Effect",
            Some("snake_case"),
            None,
            None,
            vec![
                unit("Idle"),
                FfiVariant::Struct {
                    name: "LoadFont".into(),
                    fields: vec![field("family", "String")],
                    serde_rename_all: None,
                },
            ],
        )];
        let output = render(&metas, "Effect");
        assert!(output.contains(
            "    if let single = try? decoder.singleValueContainer(), let name = try? single.decode(String.self) {"
        ));
        assert!(output.contains("      case \"idle\":\n        self = .idle"));
        assert!(output.contains(
            "      let content = try container.nestedContainer(keyedBy: FFIKey.self, forKey: key)\n      self = try .loadFont(family: content.decode(String.self, forKey: \"family\"))"
        ));
        assert!(output.contains(
            "    case .idle:\n      var single = encoder.singleValueContainer()\n      try single.encode(\"idle\")"
        ));
        assert!(output.contains(
            "      var content = container.nestedContainer(keyedBy: FFIKey.self, forKey: \"load_font\")"
        ));
    }

    #[test]
    fn struct_variant_fields_follow_serde_variant_renaming_not_the_container_rule() {
        let metas = vec![enumeration(
            "EditorEvent",
            Some("camelCase"),
            Some("type"),
            None,
            vec![
                FfiVariant::Struct {
                    name: "StateChanged".into(),
                    fields: vec![
                        field("doc_version", "u64"),
                        FfiField {
                            serde_rename: Some("commitPayload".into()),
                            ..field("commit_payload", "String")
                        },
                    ],
                    serde_rename_all: None,
                },
                FfiVariant::Struct {
                    name: "Renamed".into(),
                    fields: vec![field("page_index", "u32")],
                    serde_rename_all: Some("camelCase".into()),
                },
            ],
        )];
        let output = render(&metas, "EditorEvent");
        assert!(output.contains("    case \"stateChanged\":"));
        assert!(
            output.contains("docVersion: container.decode(UInt64.self, forKey: \"doc_version\")")
        );
        assert!(
            output.contains(
                "commitPayload: container.decode(String.self, forKey: \"commitPayload\")"
            )
        );
        assert!(output.contains("pageIndex: container.decode(UInt32.self, forKey: \"pageIndex\")"));
    }

    #[test]
    fn swift_keywords_are_escaped() {
        let metas = vec![
            structure("Settings", None, vec![field("default", "bool")]),
            enumeration(
                "InsertionOp",
                Some("snake_case"),
                Some("type"),
                None,
                vec![FfiVariant::Struct {
                    name: "Break".into(),
                    fields: vec![field("in", "u32")],
                    serde_rename_all: None,
                }],
            ),
        ];
        let settings = render(&metas, "Settings");
        assert!(settings.contains("  public var `default`: Bool"));
        assert!(settings.contains("    self.`default` = `default`"));
        let insertion = render(&metas, "InsertionOp");
        assert!(insertion.contains("  case `break`(`in`: UInt32)"));
        assert!(
            insertion
                .contains("self = try .`break`(in: container.decode(UInt32.self, forKey: \"in\"))")
        );
        assert!(insertion.contains("    case .`break`(let `in`):"));
    }

    #[test]
    fn generic_types_constrain_their_parameters() {
        let mut tri = enumeration(
            "Tri",
            Some("snake_case"),
            Some("type"),
            None,
            vec![
                unit("Absent"),
                FfiVariant::Struct {
                    name: "Uniform".into(),
                    fields: vec![field("value", "T")],
                    serde_rename_all: None,
                },
            ],
        );
        tri.generics = vec!["T".into()];
        let output = render(&[tri], "Tri");
        assert!(output.contains(
            "public enum Tri<T: Codable & Hashable & Sendable>: Codable, Hashable, Sendable {"
        ));
        assert!(output.contains("  case uniform(value: T)"));
    }

    #[test]
    fn enum_without_variants_rejects_every_payload() {
        let metas = vec![enumeration(
            "ParagraphNodeAttr",
            Some("snake_case"),
            Some("type"),
            Some("value"),
            Vec::new(),
        )];
        let output = render(&metas, "ParagraphNodeAttr");
        assert!(output.contains("ParagraphNodeAttr has no variants"));
        assert!(output.contains("  public func encode(to encoder: any Encoder) throws {}"));
    }

    #[test]
    fn variant_wrapping_an_uninhabited_enum_decodes_to_a_throw() {
        let metas = vec![
            enumeration(
                "ParagraphNodeAttr",
                Some("snake_case"),
                Some("type"),
                Some("value"),
                Vec::new(),
            ),
            enumeration(
                "RootNodeAttr",
                Some("snake_case"),
                Some("type"),
                Some("value"),
                vec![unit("Reset")],
            ),
            enumeration(
                "NodeAttr",
                Some("snake_case"),
                Some("type"),
                None,
                vec![
                    FfiVariant::Struct {
                        name: "Root".into(),
                        fields: vec![field("attr", "RootNodeAttr")],
                        serde_rename_all: None,
                    },
                    FfiVariant::Struct {
                        name: "Paragraph".into(),
                        fields: vec![field("attr", "ParagraphNodeAttr")],
                        serde_rename_all: None,
                    },
                ],
            ),
        ];
        let output = render(&metas, "NodeAttr");
        let decode = decode_body(&output);
        assert!(output.contains("  case paragraph(attr: ParagraphNodeAttr)\n"));
        assert!(decode.contains(
            "    case \"paragraph\":\n      throw DecodingError.dataCorruptedError(\n        forKey: \"type\", in: container, debugDescription: \"ParagraphNodeAttr has no variants\")\n"
        ));
        assert!(!decode.contains(".paragraph(attr:"));
        assert!(decode.contains(
            "    case \"root\":\n      self = try .root(attr: container.decode(RootNodeAttr.self, forKey: \"attr\"))"
        ));
        assert!(output.contains(
            "    case .paragraph(let attr):\n      var container = encoder.container(keyedBy: FFIKey.self)\n      try container.encode(\"paragraph\", forKey: \"type\")\n      try container.encode(attr, forKey: \"attr\")"
        ));
    }

    #[test]
    fn adjacent_and_external_variants_wrapping_an_uninhabited_enum_decode_to_a_throw() {
        let variants = || {
            vec![
                FfiVariant::Tuple {
                    name: "Wrapped".into(),
                    tys: vec!["ParagraphNodeAttr".into()],
                },
                FfiVariant::Struct {
                    name: "Nested".into(),
                    fields: vec![field("attr", "ParagraphNodeAttr")],
                    serde_rename_all: None,
                },
                FfiVariant::Struct {
                    name: "Maybe".into(),
                    fields: vec![field("attr", "Option<ParagraphNodeAttr>")],
                    serde_rename_all: None,
                },
            ]
        };
        let metas = vec![
            enumeration(
                "ParagraphNodeAttr",
                Some("snake_case"),
                Some("type"),
                Some("value"),
                Vec::new(),
            ),
            enumeration(
                "Adjacent",
                Some("snake_case"),
                Some("type"),
                Some("value"),
                variants(),
            ),
            enumeration("External", Some("snake_case"), None, None, variants()),
        ];
        for (name, key) in [("Adjacent", "\"type\""), ("External", "key")] {
            let output = render(&metas, name);
            let decode = decode_body(&output);
            for tag in ["wrapped", "nested"] {
                assert!(decode.contains(&format!(
                    "    case \"{tag}\":\n      throw DecodingError.dataCorruptedError(\n        forKey: {key}, in: container, debugDescription: \"ParagraphNodeAttr has no variants\")\n"
                )));
            }
            assert!(!decode.contains(".wrapped("));
            assert!(!decode.contains(".nested("));
            assert!(decode.contains(
                "      self = try .maybe(attr: content.decodeIfPresent(ParagraphNodeAttr.self, forKey: \"attr\"))"
            ));
            assert!(output.contains("  case wrapped(ParagraphNodeAttr)\n"));
            assert!(output.contains("    case .wrapped(let payload):\n"));
            assert!(output.contains("    case .nested(let attr):\n"));
        }
    }

    #[test]
    fn self_referencing_enum_is_indirect() {
        let metas = vec![enumeration(
            "Tree",
            None,
            Some("type"),
            None,
            vec![FfiVariant::Struct {
                name: "Node".into(),
                fields: vec![field("parent", "Option<Tree>")],
                serde_rename_all: None,
            }],
        )];
        assert!(render(&metas, "Tree").contains("public indirect enum Tree:"));
    }

    #[test]
    #[should_panic(expected = "duplicate FFI type name `Size`")]
    fn duplicate_type_names_are_rejected() {
        let metas = vec![
            structure("Size", None, Vec::new()),
            structure("Size", None, Vec::new()),
        ];
        Context::new(&metas);
    }

    #[test]
    fn variant_and_field_keys_follow_their_own_serde_rules() {
        let metas = vec![
            enumeration(
                "PasteKind",
                Some("lowercase"),
                None,
                None,
                vec![unit("HTMLPaste"), unit("PlainText")],
            ),
            enumeration(
                "ClipboardEvent",
                Some("snake_case"),
                Some("type"),
                None,
                vec![
                    unit("HTMLPaste"),
                    FfiVariant::Struct {
                        name: "Commit".into(),
                        fields: vec![field("commit_payload", "String")],
                        serde_rename_all: Some("camelCase".into()),
                    },
                ],
            ),
            structure(
                "Draft",
                Some("camelCase"),
                vec![field("commit_payload", "String")],
            ),
        ];
        let raw = render(&metas, "PasteKind");
        assert!(raw.contains("  case htmlPaste = \"htmlpaste\"\n"), "{raw}");
        assert!(raw.contains("  case plainText = \"plaintext\"\n"), "{raw}");
        let tagged = render(&metas, "ClipboardEvent");
        assert!(
            tagged.contains("    case \"h_t_m_l_paste\":\n      self = .htmlPaste\n"),
            "{tagged}"
        );
        assert!(
            tagged.contains("      try container.encode(\"h_t_m_l_paste\", forKey: \"type\")"),
            "{tagged}"
        );
        assert!(
            tagged.contains(
                "commitPayload: container.decode(String.self, forKey: \"commitPayload\")"
            ),
            "{tagged}"
        );
        let draft = render(&metas, "Draft");
        assert!(
            draft.contains(
                "    commitPayload = try container.decode(String.self, forKey: \"commitPayload\")"
            ),
            "{draft}"
        );
    }

    #[test]
    fn variant_names_follow_serde_variant_rules() {
        for (original, lower, upper, camel, snake, screaming, kebab, screaming_kebab) in [
            (
                "Outcome", "outcome", "OUTCOME", "outcome", "outcome", "OUTCOME", "outcome",
                "OUTCOME",
            ),
            (
                "VeryTasty",
                "verytasty",
                "VERYTASTY",
                "veryTasty",
                "very_tasty",
                "VERY_TASTY",
                "very-tasty",
                "VERY-TASTY",
            ),
            ("A", "a", "A", "a", "a", "A", "a", "A"),
            ("Z42", "z42", "Z42", "z42", "z42", "Z42", "z42", "Z42"),
            (
                "HTMLPaste",
                "htmlpaste",
                "HTMLPASTE",
                "hTMLPaste",
                "h_t_m_l_paste",
                "H_T_M_L_PASTE",
                "h-t-m-l-paste",
                "H-T-M-L-PASTE",
            ),
        ] {
            let rename = |rule| RenameRule::parse(rule, "Sample").apply_to_variant(original);
            assert_eq!(rename(None), original);
            assert_eq!(rename(Some("lowercase")), lower);
            assert_eq!(rename(Some("UPPERCASE")), upper);
            assert_eq!(rename(Some("PascalCase")), original);
            assert_eq!(rename(Some("camelCase")), camel);
            assert_eq!(rename(Some("snake_case")), snake);
            assert_eq!(rename(Some("SCREAMING_SNAKE_CASE")), screaming);
            assert_eq!(rename(Some("kebab-case")), kebab);
            assert_eq!(rename(Some("SCREAMING-KEBAB-CASE")), screaming_kebab);
        }
    }

    #[test]
    fn field_names_follow_serde_field_rules() {
        for (original, upper, pascal, camel, screaming, kebab, screaming_kebab) in [
            (
                "outcome", "OUTCOME", "Outcome", "outcome", "OUTCOME", "outcome", "OUTCOME",
            ),
            (
                "very_tasty",
                "VERY_TASTY",
                "VeryTasty",
                "veryTasty",
                "VERY_TASTY",
                "very-tasty",
                "VERY-TASTY",
            ),
            ("a", "A", "A", "a", "A", "a", "A"),
            ("z42", "Z42", "Z42", "z42", "Z42", "z42", "Z42"),
            (
                "commit_payload",
                "COMMIT_PAYLOAD",
                "CommitPayload",
                "commitPayload",
                "COMMIT_PAYLOAD",
                "commit-payload",
                "COMMIT-PAYLOAD",
            ),
        ] {
            let rename = |rule| RenameRule::parse(rule, "Sample").apply_to_field(original);
            assert_eq!(rename(None), original);
            assert_eq!(rename(Some("lowercase")), original);
            assert_eq!(rename(Some("UPPERCASE")), upper);
            assert_eq!(rename(Some("PascalCase")), pascal);
            assert_eq!(rename(Some("camelCase")), camel);
            assert_eq!(rename(Some("snake_case")), original);
            assert_eq!(rename(Some("SCREAMING_SNAKE_CASE")), screaming);
            assert_eq!(rename(Some("kebab-case")), kebab);
            assert_eq!(rename(Some("SCREAMING-KEBAB-CASE")), screaming_kebab);
        }
    }

    #[test]
    #[should_panic(expected = "Mode: unknown serde rename rule `Title Case`")]
    fn unknown_rename_rules_are_rejected() {
        let metas = vec![enumeration(
            "Mode",
            Some("Title Case"),
            None,
            None,
            vec![unit("On")],
        )];
        render(&metas, "Mode");
    }

    #[test]
    fn dictionary_keys_that_encode_as_object_keys_are_accepted() {
        let metas = vec![
            FfiMeta {
                name: "Dot".into(),
                kind: FfiKind::Custom {
                    target: "String".into(),
                },
                serde_rename_all: None,
                generics: Vec::new(),
            },
            enumeration(
                "ModifierType",
                Some("snake_case"),
                None,
                None,
                vec![unit("Bold")],
            ),
            structure("Size", None, Vec::new()),
            structure(
                "Lookup",
                Some("snake_case"),
                vec![
                    field("by_name", "BTreeMap<String,Size>"),
                    field("by_index", "HashMap<usize,Size>"),
                    field("by_type", "BTreeMap<ModifierType,Size>"),
                    field("by_dot", "imbl::HashMap<Dot,Size>"),
                ],
            ),
        ];
        let output = render(&metas, "Lookup");
        assert!(
            output.contains("  public var byName: [String: Size]\n"),
            "{output}"
        );
        assert!(
            output.contains("  public var byIndex: [Int: Size]\n"),
            "{output}"
        );
        assert!(
            output.contains("  public var byType: [ModifierType: Size]\n"),
            "{output}"
        );
        assert!(
            output.contains("  public var byDot: [String: Size]\n"),
            "{output}"
        );
    }

    #[test]
    #[should_panic(expected = "Lookup.by_id: unsupported dictionary key type `u32`")]
    fn dictionary_keys_that_encode_as_arrays_are_rejected() {
        let metas = vec![structure(
            "Lookup",
            None,
            vec![field("by_id", "BTreeMap<u32,String>")],
        )];
        render(&metas, "Lookup");
    }

    #[test]
    #[should_panic(expected = "Timing.delay: unknown type `Duration`")]
    fn unknown_bare_type_names_are_rejected() {
        let metas = vec![structure(
            "Timing",
            Some("snake_case"),
            vec![field("delay", "Duration")],
        )];
        render(&metas, "Timing");
    }

    #[test]
    fn generic_parameters_resolve_inside_their_own_type() {
        let mut op = structure(
            "Op",
            Some("snake_case"),
            vec![field("payload", "P"), field("history", "Vec<P>")],
        );
        op.generics = vec!["P".into()];
        let output = render(&[op], "Op");
        assert!(
            output.contains(
                "public struct Op<P: Codable & Hashable & Sendable>: Codable, Hashable, Sendable {"
            ),
            "{output}"
        );
        assert!(output.contains("  public var payload: P\n"), "{output}");
        assert!(output.contains("  public var history: [P]\n"), "{output}");
    }

    #[test]
    fn adjacently_tagged_unit_variant_carries_no_content() {
        let metas = vec![enumeration(
            "Toggle",
            Some("snake_case"),
            Some("type"),
            Some("value"),
            vec![
                unit("Off"),
                FfiVariant::Tuple {
                    name: "Level".into(),
                    tys: vec!["u32".into()],
                },
            ],
        )];
        let output = render(&metas, "Toggle");
        let decode = decode_body(&output);
        assert!(
            decode.contains("    case \"off\":\n      self = .off\n    case \"level\":"),
            "{output}"
        );
        assert!(
            output.contains(
                "    case .off:\n      try container.encode(\"off\", forKey: \"type\")\n    case .level(let payload):"
            ),
            "{output}"
        );
    }

    #[test]
    fn fieldless_struct_variants_encode_an_empty_object() {
        let variants = || {
            vec![FfiVariant::Struct {
                name: "Empty".into(),
                fields: Vec::new(),
                serde_rename_all: None,
            }]
        };
        let metas = vec![
            enumeration(
                "Adjacent",
                Some("snake_case"),
                Some("type"),
                Some("value"),
                variants(),
            ),
            enumeration("External", Some("snake_case"), None, None, variants()),
        ];
        let adjacent = render(&metas, "Adjacent");
        assert!(
            adjacent.contains(
                "    case .empty:\n      try container.encode(\"empty\", forKey: \"type\")\n      _ = container.nestedContainer(keyedBy: FFIKey.self, forKey: \"value\")\n"
            ),
            "{adjacent}"
        );
        let external = render(&metas, "External");
        assert!(
            external.contains(
                "    case .empty:\n      var container = encoder.container(keyedBy: FFIKey.self)\n      _ = container.nestedContainer(keyedBy: FFIKey.self, forKey: \"empty\")\n"
            ),
            "{external}"
        );
    }

    #[test]
    fn externally_tagged_newtype_variant_nests_the_payload_under_its_key() {
        let metas = vec![enumeration(
            "Effect",
            Some("snake_case"),
            None,
            None,
            vec![FfiVariant::Tuple {
                name: "SetZoom".into(),
                tys: vec!["f32".into()],
            }],
        )];
        let output = render(&metas, "Effect");
        assert!(output.contains("  case setZoom(Float)\n"), "{output}");
        assert!(
            decode_body(&output).contains(
                "    case \"set_zoom\":\n      self = try .setZoom(container.decode(Float.self, forKey: key))\n"
            ),
            "{output}"
        );
        assert!(
            output.contains(
                "    case .setZoom(let payload):\n      var container = encoder.container(keyedBy: FFIKey.self)\n      try container.encode(payload, forKey: \"set_zoom\")\n"
            ),
            "{output}"
        );
    }

    #[test]
    fn field_of_an_all_defaulted_struct_defaults_to_its_empty_initializer() {
        let metas = vec![
            structure(
                "Margins",
                Some("snake_case"),
                vec![defaulted("top", "u32"), defaulted("bottom", "u32")],
            ),
            structure(
                "Layout",
                Some("snake_case"),
                vec![defaulted("margins", "Margins")],
            ),
        ];
        let output = render(&metas, "Layout");
        assert!(
            output.contains("  public init(margins: Margins = Margins()) {"),
            "{output}"
        );
        assert!(
            output.contains(
                "    margins = try container.decodeIfPresent(Margins.self, forKey: \"margins\") ?? Margins()"
            ),
            "{output}"
        );
    }

    #[test]
    fn string_enum_keyed_map_is_a_swift_dictionary() {
        let metas = vec![
            enumeration(
                "ModifierType",
                Some("snake_case"),
                None,
                None,
                vec![unit("Bold"), unit("Italic")],
            ),
            structure("Modifier", None, Vec::new()),
            structure(
                "Styles",
                Some("snake_case"),
                vec![field("modifiers", "BTreeMap<ModifierType,Modifier>")],
            ),
        ];
        let output = render(&metas, "Styles");
        assert!(
            output.contains("  public var modifiers: [ModifierType: Modifier]\n"),
            "{output}"
        );
    }

    #[test]
    fn generic_newtype_variants_carry_their_type_parameter() {
        for (name, tag, content, key) in [
            ("Adjacent", Some("type"), Some("value"), "\"value\""),
            ("External", None, None, "key"),
        ] {
            let mut maybe = enumeration(
                name,
                Some("snake_case"),
                tag,
                content,
                vec![FfiVariant::Tuple {
                    name: "Some".into(),
                    tys: vec!["T".into()],
                }],
            );
            maybe.generics = vec!["T".into()];
            let output = render(&[maybe], name);
            assert!(output.contains("  case some(T)\n"), "{output}");
            assert!(
                decode_body(&output).contains(&format!(
                    "      self = try .some(container.decode(T.self, forKey: {key}))\n"
                )),
                "{output}"
            );
        }
    }

    #[test]
    #[should_panic(expected = "Span.range: unknown type `std::ops::Range`")]
    fn unknown_generic_type_names_are_rejected() {
        let metas = vec![structure(
            "Span",
            Some("snake_case"),
            vec![field("range", "std::ops::Range<u32>")],
        )];
        render(&metas, "Span");
    }

    #[test]
    fn declared_generic_types_accept_arguments() {
        let mut changeset = structure(
            "Changeset",
            Some("snake_case"),
            vec![field("ops", "Vec<P>")],
        );
        changeset.generics = vec!["P".into()];
        let mut batch = structure(
            "Batch",
            Some("snake_case"),
            vec![
                field("pending", "Changeset<P>"),
                field("labels", "Option<Vec<String>>"),
                field("sizes", "BTreeMap<String,u32>"),
            ],
        );
        batch.generics = vec!["P".into()];
        let output = render(&[changeset, batch], "Batch");
        assert!(
            output.contains("  public var pending: Changeset<P>\n"),
            "{output}"
        );
        assert!(
            output.contains("  public var labels: [String]?\n"),
            "{output}"
        );
        assert!(
            output.contains("  public var sizes: [String: UInt32]\n"),
            "{output}"
        );
    }

    #[test]
    #[should_panic(expected = "Layout.margins: no Swift default for `Margins`")]
    fn field_of_a_partly_defaulted_struct_cannot_default() {
        let metas = vec![
            structure(
                "Margins",
                Some("snake_case"),
                vec![defaulted("top", "u32"), field("bottom", "u32")],
            ),
            structure(
                "Layout",
                Some("snake_case"),
                vec![defaulted("margins", "Margins")],
            ),
        ];
        render(&metas, "Layout");
    }

    #[test]
    #[should_panic(expected = "Event::Changed.delay: unknown type `Duration`")]
    fn unknown_types_in_struct_variants_name_their_variant() {
        let metas = vec![enumeration(
            "Event",
            Some("snake_case"),
            Some("type"),
            None,
            vec![FfiVariant::Struct {
                name: "Changed".into(),
                fields: vec![field("delay", "Duration")],
                serde_rename_all: None,
            }],
        )];
        render(&metas, "Event");
    }

    #[test]
    #[should_panic(expected = "Layout.margins: no Swift default for `Margins`")]
    fn boxed_field_of_a_partly_defaulted_struct_cannot_default() {
        let metas = vec![
            structure(
                "Margins",
                Some("snake_case"),
                vec![defaulted("top", "u32"), field("bottom", "u32")],
            ),
            structure(
                "Layout",
                Some("snake_case"),
                vec![defaulted("margins", "Box<Margins>")],
            ),
        ];
        render(&metas, "Layout");
    }

    #[test]
    #[should_panic(expected = "Span.bounds: unsupported type in FFI metadata")]
    fn tuple_fields_name_their_owner() {
        let metas = vec![structure(
            "Span",
            Some("snake_case"),
            vec![field("bounds", "(u32,u32)")],
        )];
        render(&metas, "Span");
    }

    #[test]
    #[should_panic(expected = "Buffer.items: SmallVec expects an array type argument")]
    fn small_vec_without_an_array_names_its_owner() {
        let metas = vec![structure(
            "Buffer",
            Some("snake_case"),
            vec![field("items", "SmallVec<u32>")],
        )];
        render(&metas, "Buffer");
    }

    #[test]
    #[should_panic(expected = "Sample.value: failed to parse type `&'staticstr`")]
    fn unparsable_types_name_their_owner() {
        let metas = vec![structure(
            "Sample",
            Some("snake_case"),
            vec![field("value", "&'staticstr")],
        )];
        render(&metas, "Sample");
    }

    #[test]
    #[should_panic(expected = "Event::Changed: unknown serde rename rule `Title Case`")]
    fn unknown_variant_rename_rules_name_their_variant() {
        let metas = vec![enumeration(
            "Event",
            Some("snake_case"),
            Some("type"),
            None,
            vec![FfiVariant::Struct {
                name: "Changed".into(),
                fields: vec![field("page_index", "u32")],
                serde_rename_all: Some("Title Case".into()),
            }],
        )];
        render(&metas, "Event");
    }
}
