use std::collections::HashMap;
use std::path::Path;

use heck::ToLowerCamelCase;

use crate::meta::{
    FfiInterface, FfiMethod, FfiParam, FfiParamType, FfiReturnType, FfiScalarParam, FfiScalarReturn,
};
use crate::objc::{swift_call_args, swift_param_decl};

pub fn generate_all(
    interfaces: &[FfiInterface],
    custom_types: &HashMap<String, String>,
    output_dir: &Path,
) {
    std::fs::create_dir_all(output_dir).expect("failed to create output directory");

    let content = generate_editor_swift(interfaces, custom_types);
    let path = output_dir.join("Editor.swift");
    std::fs::write(&path, content).expect("failed to write Editor.swift");
}

fn generate_editor_swift(
    interfaces: &[FfiInterface],
    custom_types: &HashMap<String, String>,
) -> String {
    let mut out = String::new();
    out.push_str("// This file is auto-generated by editor-bindgen. Do not edit.\n");
    out.push_str("\n");
    out.push_str("import Foundation\n");

    for iface in interfaces {
        out.push('\n');
        out.push_str(&generate_class(iface, custom_types));
    }

    out
}

fn has_constructor(iface: &FfiInterface) -> bool {
    iface.methods.iter().any(|m| m.is_constructor)
}

fn generate_class(iface: &FfiInterface, custom_types: &HashMap<String, String>) -> String {
    let native_name = format!("Native{}", iface.name);
    let inner_type = &iface.name;
    let is_host = has_constructor(iface);

    let mut out = String::new();
    if is_host {
        out.push_str(&format!(
            "@objc public class {}: NSObject, @unchecked Sendable {{\n",
            native_name
        ));
    } else {
        out.push_str(&format!(
            "@objc public class {}: NSObject {{\n",
            native_name
        ));
    }

    if is_host {
        out.push_str(&format!("    private var inner: {}?\n", inner_type));
        out.push('\n');
        out.push_str("    @objc public override init() { super.init() }\n");
    } else {
        out.push_str(&format!("    private let inner: {}\n", inner_type));
        out.push('\n');
        out.push_str(&format!("    init(inner: {}) {{\n", inner_type));
        out.push_str("        self.inner = inner\n");
        out.push_str("        super.init()\n");
        out.push_str("    }\n");
    }

    for method in &iface.methods {
        out.push('\n');
        if method.is_constructor {
            out.push_str(&generate_constructor_method(method, iface, custom_types));
        } else {
            out.push_str(&generate_regular_method(method, iface, custom_types));
        }
    }

    out.push_str("}\n");
    out
}

fn generate_constructor_method(
    method: &FfiMethod,
    iface: &FfiInterface,
    custom_types: &HashMap<String, String>,
) -> String {
    let inner_type = &iface.name;
    let mut out = String::new();

    let user_params = swift_param_decl(&method.params, |p| swift_param_type(&p.ty, custom_types));
    let all_params = if user_params.is_empty() {
        "completion: @escaping @Sendable (NSError?) -> Void".to_string()
    } else {
        format!(
            "{}, completion: @escaping @Sendable (NSError?) -> Void",
            user_params
        )
    };

    out.push_str(&format!(
        "    @objc public func create({}) {{\n",
        all_params
    ));
    out.push_str("        Task {\n");
    out.push_str("            do {\n");

    let call_args = swift_call_args(&method.params, |p| param_conversion(p, custom_types));
    let create_call = if call_args.is_empty() {
        format!("{}.create()", inner_type)
    } else {
        format!("{}.create({})", inner_type, call_args)
    };

    out.push_str(&format!(
        "                self.inner = try await {}\n",
        create_call
    ));
    out.push_str("                completion(nil)\n");
    out.push_str("            } catch {\n");
    out.push_str("                completion(error as NSError)\n");
    out.push_str("            }\n");
    out.push_str("        }\n");
    out.push_str("    }\n");

    out
}

fn generate_regular_method(
    method: &FfiMethod,
    iface: &FfiInterface,
    custom_types: &HashMap<String, String>,
) -> String {
    let is_host = has_constructor(iface);
    let swift_name = method.name.to_lower_camel_case();

    let user_params = swift_param_decl(&method.params, |p| swift_param_type(&p.ty, custom_types));
    let error_param = "error: AutoreleasingUnsafeMutablePointer<NSError?>";
    let all_params = if user_params.is_empty() {
        error_param.to_string()
    } else {
        format!("{}, {}", user_params, error_param)
    };

    let ret_swift = swift_return_type(&method.return_type, custom_types);
    let ret_part = if ret_swift.is_empty() {
        String::new()
    } else {
        let opt = if ret_swift.ends_with('?') {
            ret_swift.clone()
        } else {
            format!("{}?", ret_swift)
        };
        format!(" -> {}", opt)
    };

    let sig = format!(
        "    @objc public func {}({}){}",
        swift_name, all_params, ret_part
    );

    let call_args = swift_call_args(&method.params, |p| param_conversion(p, custom_types));
    let call_expr = if call_args.is_empty() {
        format!("inner.{}()", swift_name)
    } else {
        format!("inner.{}({})", swift_name, call_args)
    };

    let has_return = !ret_swift.is_empty();
    let return_expr = build_return_expr(&method.return_type, &call_expr, custom_types);

    let mut out = String::new();
    out.push_str(&format!("{} {{\n", sig));

    if is_host {
        out.push_str("        guard let inner else {\n");
        out.push_str("            error.pointee = NSError(domain: \"EditorBridge\", code: -1,\n");
        out.push_str(
            "                userInfo: [NSLocalizedDescriptionKey: \"EditorHost not initialized\"])\n",
        );
        if has_return {
            out.push_str("            return nil\n");
        } else {
            out.push_str("            return\n");
        }
        out.push_str("        }\n");
    }

    out.push_str("        do {\n");
    out.push_str(&format!("            {}\n", return_expr));
    out.push_str("        } catch let e {\n");
    out.push_str("            error.pointee = e as NSError\n");
    if has_return {
        out.push_str("            return nil\n");
    }
    out.push_str("        }\n");

    out.push_str("    }\n");
    out
}

fn build_return_expr(
    ret: &FfiReturnType,
    call_expr: &str,
    _custom_types: &HashMap<String, String>,
) -> String {
    match ret {
        FfiReturnType::Unit => format!("try {}", call_expr),
        FfiReturnType::Owned(name) => {
            let native_name = format!("Native{}", name);
            format!("return {}(inner: try {})", native_name, call_expr)
        }
        _ => format!("return try {}", call_expr),
    }
}

fn swift_param_type(ty: &FfiParamType, custom_types: &HashMap<String, String>) -> String {
    match ty {
        FfiParamType::Primitive(p) => resolve_swift_primitive(p, custom_types),
        FfiParamType::Complex(_) => "String".into(),
        FfiParamType::Vec(inner) => {
            if matches!(inner, FfiScalarParam::Primitive(p) if p == "u8") {
                "Data".into()
            } else {
                "[String]".into()
            }
        }
        FfiParamType::Option(inner) => {
            let base = match inner {
                FfiScalarParam::Primitive(p) => resolve_swift_primitive(p, custom_types),
                FfiScalarParam::Complex(_) => "String".into(),
            };
            format!("{}?", base)
        }
    }
}

fn swift_return_type(ret: &FfiReturnType, custom_types: &HashMap<String, String>) -> String {
    match ret {
        FfiReturnType::Unit => String::new(),
        FfiReturnType::Primitive(p) => resolve_swift_primitive(p, custom_types),
        FfiReturnType::Complex(_) => "String".into(),
        FfiReturnType::Owned(name) => format!("Native{}", name),
        FfiReturnType::Vec(inner) => match inner {
            FfiScalarReturn::Primitive(p) if p == "u8" => "Data".into(),
            FfiScalarReturn::Complex(_) | FfiScalarReturn::Owned(_) => "[String]".into(),
            FfiScalarReturn::Primitive(p) => {
                format!("[{}]", resolve_swift_primitive(p, custom_types))
            }
        },
        FfiReturnType::Option(inner) => {
            let base = match inner {
                FfiScalarReturn::Primitive(p) => resolve_swift_primitive(p, custom_types),
                FfiScalarReturn::Complex(_) => "String".into(),
                FfiScalarReturn::Owned(name) => format!("Native{}", name),
            };
            format!("{}?", base)
        }
    }
}

fn param_conversion(param: &FfiParam, custom_types: &HashMap<String, String>) -> String {
    let name = param.name.to_lower_camel_case();
    match &param.ty {
        FfiParamType::Primitive(p) => {
            let resolved = custom_types
                .get(p.as_str())
                .map(|s| s.as_str())
                .unwrap_or(p.as_str());
            match resolved {
                "u32" => format!("UInt32({})", name),
                "u16" => format!("UInt16({})", name),
                "u64" => format!("UInt64({})", name),
                _ => name,
            }
        }
        _ => name,
    }
}

fn resolve_swift_primitive(name: &str, custom_types: &HashMap<String, String>) -> String {
    let resolved = custom_types.get(name).map(|s| s.as_str()).unwrap_or(name);
    match resolved {
        "bool" => "Bool".into(),
        "u16" | "i16" | "u32" | "i32" => "Int32".into(),
        "u64" | "i64" | "usize" => "Int64".into(),
        "f32" => "Float".into(),
        "f64" => "Double".into(),
        "String" => "String".into(),
        other => other.into(),
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::meta::*;

    fn make_custom_types() -> HashMap<String, String> {
        let mut m = HashMap::new();
        m.insert("PlatformHandle".into(), "u64".into());
        m
    }

    fn empty_ct() -> HashMap<String, String> {
        HashMap::new()
    }

    fn editor_host_iface() -> FfiInterface {
        FfiInterface {
            name: "EditorHost".into(),
            methods: vec![
                FfiMethod {
                    name: "create".into(),
                    is_async: true,
                    is_constructor: true,
                    params: vec![FfiParam {
                        name: "kind".into(),
                        ty: FfiParamType::Option(FfiScalarParam::Complex("BackendKind".into())),
                    }],
                    return_type: FfiReturnType::Owned("EditorHost".into()),
                },
                FfiMethod {
                    name: "create_editor".into(),
                    is_async: false,
                    is_constructor: false,
                    params: vec![
                        FfiParam {
                            name: "doc".into(),
                            ty: FfiParamType::Complex("Doc".into()),
                        },
                        FfiParam {
                            name: "selection".into(),
                            ty: FfiParamType::Complex("Selection".into()),
                        },
                        FfiParam {
                            name: "viewport".into(),
                            ty: FfiParamType::Complex("Viewport".into()),
                        },
                    ],
                    return_type: FfiReturnType::Owned("Editor".into()),
                },
                FfiMethod {
                    name: "load_icu_data".into(),
                    is_async: false,
                    is_constructor: false,
                    params: vec![FfiParam {
                        name: "data".into(),
                        ty: FfiParamType::Vec(FfiScalarParam::Primitive("u8".into())),
                    }],
                    return_type: FfiReturnType::Unit,
                },
            ],
        }
    }

    fn editor_iface() -> FfiInterface {
        FfiInterface {
            name: "Editor".into(),
            methods: vec![
                FfiMethod {
                    name: "enqueue".into(),
                    is_async: false,
                    is_constructor: false,
                    params: vec![FfiParam {
                        name: "message".into(),
                        ty: FfiParamType::Complex("Message".into()),
                    }],
                    return_type: FfiReturnType::Unit,
                },
                FfiMethod {
                    name: "cursor".into(),
                    is_async: false,
                    is_constructor: false,
                    params: vec![],
                    return_type: FfiReturnType::Option(FfiScalarReturn::Complex("PageRect".into())),
                },
            ],
        }
    }

    #[test]
    fn no_throws_keyword() {
        let iface = editor_iface();
        let output = generate_class(&iface, &empty_ct());
        assert!(!output.contains(" throws"));
    }

    #[test]
    fn error_parameter_on_all_methods() {
        let iface = editor_iface();
        let output = generate_class(&iface, &empty_ct());
        assert!(output.contains("error: AutoreleasingUnsafeMutablePointer<NSError?>"));
        assert!(output.contains(
            "func enqueue(message: String, error: AutoreleasingUnsafeMutablePointer<NSError?>)"
        ));
        assert!(output.contains(
            "func cursor(error: AutoreleasingUnsafeMutablePointer<NSError?>) -> String?"
        ));
    }

    #[test]
    fn do_catch_pattern() {
        let iface = editor_iface();
        let output = generate_class(&iface, &empty_ct());
        assert!(output.contains("do {"));
        assert!(output.contains("} catch let e {"));
        assert!(output.contains("error.pointee = e as NSError"));
    }

    #[test]
    fn host_guard_uses_error_pointee() {
        let iface = editor_host_iface();
        let output = generate_class(&iface, &empty_ct());
        assert!(output.contains("error.pointee = NSError(domain: \"EditorBridge\""));
        assert!(output.contains("EditorHost not initialized\"])\n            return\n"));
    }

    #[test]
    fn option_return_is_nullable() {
        let iface = editor_iface();
        let output = generate_class(&iface, &empty_ct());
        assert!(output.contains("-> String?"));
        assert!(!output.contains("-> String??"));
    }

    #[test]
    fn non_option_return_becomes_nullable() {
        let iface = editor_host_iface();
        let output = generate_class(&iface, &empty_ct());
        assert!(output.contains("-> NativeEditor?"));
    }

    #[test]
    fn sendable_on_host_only() {
        let host = generate_class(&editor_host_iface(), &empty_ct());
        let editor = generate_class(&editor_iface(), &empty_ct());
        assert!(host.contains("@unchecked Sendable"));
        assert!(!editor.contains("@unchecked Sendable"));
    }

    #[test]
    fn platform_handle_resolves() {
        let ct = make_custom_types();
        assert_eq!(resolve_swift_primitive("PlatformHandle", &ct), "Int64");
    }

    #[test]
    fn constructor_passes_params_to_create() {
        let iface = editor_host_iface();
        let output = generate_class(&iface, &empty_ct());
        assert!(
            output.contains("func create(kind: String?, completion:"),
            "Expected kind param in constructor:\n{}",
            output
        );
        assert!(
            output.contains("EditorHost.create(kind: kind)"),
            "Expected kind forwarded to inner create:\n{}",
            output
        );
    }
}
