export const LIGHT_VARIANTS = [
  'white',
  'flexoki',
  'everforest',
  'gruvbox-material',
  'rose-pine-dawn',
  'cupcake',
  'sakura',
  'noctis-lilac',
  'catppuccin-latte',
  'silk',
  'atelier-seaside',
  'atelier-lakeside',
] as const;
export const DARK_VARIANTS = [
  'black',
  'flexoki',
  'github',
  'rose-pine',
  'catppuccin-mocha',
  'dracula',
  'nightfox',
  'nord',
  'everforest',
  'monokai',
  'melange',
  'gruvbox-material',
] as const;

export type LightVariant = (typeof LIGHT_VARIANTS)[number];
export type DarkVariant = (typeof DARK_VARIANTS)[number];
export type ThemeVariant = `light-${LightVariant}` | `dark-${DarkVariant}`;

export const DEFAULT_LIGHT_VARIANT: LightVariant = 'white';
export const DEFAULT_DARK_VARIANT: DarkVariant = 'black';

export const VARIANT_LABELS: Record<ThemeVariant, string> = {
  'light-white': 'White',
  'light-flexoki': 'Flexoki Light',
  'light-everforest': 'Everforest Light',
  'light-gruvbox-material': 'Gruvbox Light',
  'light-rose-pine-dawn': 'Rose Pine Dawn',
  'light-cupcake': 'Cupcake',
  'light-sakura': 'Sakura',
  'light-noctis-lilac': 'Noctis Lilac',
  'light-catppuccin-latte': 'Catppuccin Latte',
  'light-silk': 'Silk Light',
  'light-atelier-seaside': 'Atelier Seaside L',
  'light-atelier-lakeside': 'Atelier Lakeside L',
  'dark-black': 'Black',
  'dark-flexoki': 'Flexoki',
  'dark-github': 'GitHub',
  'dark-rose-pine': 'Rose Pine',
  'dark-catppuccin-mocha': 'Catppuccin Mocha',
  'dark-dracula': 'Dracula',
  'dark-nightfox': 'Nightfox',
  'dark-nord': 'Nord',
  'dark-everforest': 'Everforest',
  'dark-monokai': 'Monokai',
  'dark-melange': 'Melange',
  'dark-gruvbox-material': 'Gruvbox',
};

export const VARIANT_CANVAS: Record<ThemeVariant, string> = {
  'light-white': '#f9fafd',
  'light-flexoki': '#f2f0e5',
  'light-everforest': '#efebd4',
  'light-gruvbox-material': '#f2e5bc',
  'light-rose-pine-dawn': '#fffaf3',
  'light-cupcake': '#f8eeef',
  'light-sakura': '#f8e2e7',
  'light-noctis-lilac': '#edecf8',
  'light-catppuccin-latte': '#e6e9ef',
  'light-silk': '#e6eeec',
  'light-atelier-seaside': '#daf4da',
  'light-atelier-lakeside': '#ceeeff',
  'dark-black': '#0a0b0e',
  'dark-flexoki': '#1c1b1a',
  'dark-github': '#161b22',
  'dark-rose-pine': '#1f1d2e',
  'dark-catppuccin-mocha': '#181825',
  'dark-dracula': '#323443',
  'dark-nightfox': '#131a24',
  'dark-nord': '#3b4252',
  'dark-everforest': '#232a2e',
  'dark-monokai': '#1e1f1c',
  'dark-melange': '#34302c',
  'dark-gruvbox-material': '#252423',
};

export const VARIANT_SELECTION: Record<ThemeVariant, string> = {
  'light-white': '#99ccff',
  'light-flexoki': '#c9c7c2',
  'light-everforest': '#c1d08d',
  'light-gruvbox-material': '#f7b792',
  'light-rose-pine-dawn': '#d3bcee',
  'light-cupcake': '#debbd7',
  'light-sakura': '#dab7f3',
  'light-noctis-lilac': '#bfc0ff',
  'light-catppuccin-latte': '#cdbbfb',
  'light-silk': '#7bd9df',
  'light-atelier-seaside': '#a5d7a1',
  'light-atelier-lakeside': '#8dd1fa',
  'dark-black': '#99ccff',
  'dark-flexoki': '#c7c7cc',
  'dark-github': '#a6c9ff',
  'dark-rose-pine': '#d5b9f7',
  'dark-catppuccin-mocha': '#d5b9f7',
  'dark-dracula': '#d2baf9',
  'dark-nightfox': '#a3caff',
  'dark-nord': '#99d2e2',
  'dark-everforest': '#b9d292',
  'dark-monokai': '#fbafbd',
  'dark-melange': '#f3ba8c',
  'dark-gruvbox-material': '#f7b791',
};
