import { defineTokens } from '@pandacss/dev';

export const zIndex = defineTokens.zIndex({
  0: { value: '0' },
  1: { value: '1' },
  2: { value: '2' },
  3: { value: '3' },
  4: { value: '4' },
  5: { value: '5' },
  10: { value: '10' },
  20: { value: '20' },
  30: { value: '30' },
  40: { value: '40' },
  50: { value: '50' },
  ground: { value: '0' },
  underEditor: { value: '40' },
  editor: { value: '50' },
  overEditor: { value: '60' },
  widget: { value: '65' },
  underPanel: { value: '68' },
  panel: { value: '70' },
  overPanel: { value: '72' },
  sidebar: { value: '75' },
  menu: { value: '80' },
  modal: { value: '80' },
  ghost: { value: '85' },
  tooltip: { value: '90' },
  tip: { value: '100' },
  notification: { value: '150' },
});
