default_platform(:android)

platform :android do
  desc "Set up signing credentials"
  lane :setup do
    sh "echo $KEYSTORE | base64 -d > ../keystore-release.jks"
  end

  desc "Build and upload to beta"
  lane :beta do
    latest_build_number = google_play_track_version_codes(track: "internal")[0]

    gradle(
      project_dir: "..",
      task: "android:bundleRelease",
      properties: { "versionCode" => latest_build_number + 1 }
    )

    upload_to_play_store(
      track: "internal",
    )
  end

end
