query EditorScreen_Query($entityId: ID!) {
  me @catch(to: THROW) {
    id
    role
    name
    preferences
    avatar {
      ...Img_image
    }
    ...TextReplacementLoader_user
  }

  entity(entityId: $entityId) @catch(to: THROW) {
    id

    user {
      id
    }

    site {
      id
    }

    ...EntityIcon_entity

    node {
      __typename

      ... on Document {
        id
        locked
        nullableTitle
        subtitle
        layoutMode
        state {
          updatedAt
        }
        toolbarFontFamilies: fontFamilies(sources: [DEFAULT, USER, FALLBACK]) {
          ...EditorSettingsFontFamily_family
        }
        ...FontLoader_Document
      }
    }
  }
}

mutation EditorScreen_ViewEntity_Mutation($input: ViewEntityInput!, $siteId: ID!) {
  viewEntity(input: $input) {
    id

    user {
      id

      recentlyViewedEntities(siteId: $siteId) {
        id
      }
    }
  }
}

mutation EditorScreen_UpdateDocument_Mutation($input: UpdateDocumentInput!) {
  updateDocument(input: $input) {
    id
    nullableTitle
    subtitle
  }
}

mutation EditorScreen_UnfurlEmbed_Mutation($input: UnfurlEmbedInput!) {
  unfurlEmbed(input: $input) {
    id
    url
    title
    description
    thumbnailUrl
    html
  }
}
