import type { Theme } from '@typie/editor';

const colorToU32 = (color: string): number => {
  const clean = color.replace('#', '');
  if (clean.length !== 6) {
    return 0x00_00_00_ff;
  }
  const r = Number.parseInt(clean.slice(0, 2), 16);
  const g = Number.parseInt(clean.slice(2, 4), 16);
  const b = Number.parseInt(clean.slice(4, 6), 16);
  return ((r << 24) | (g << 16) | (b << 8) | 0xff) >>> 0;
};

const COLORS: Record<string, string> = {
  'ui.surface.default': '#ffffff',
  'ui.surface.subtle': '#f9fafd',
  'ui.surface.muted': '#f3f4f9',
  'ui.surface.dark': '#3e3f47',
  'ui.text.default': '#17181c',
  'ui.text.subtle': '#3e3f47',
  'ui.text.muted': '#51525b',
  'ui.text.faint': '#70717b',
  'ui.text.disabled': '#9e9fa9',
  'ui.text.bright': '#ffffff',
  'ui.text.danger': '#f23864',
  'ui.text.success': '#00714a',
  'ui.text.link': '#5661f3',
  'ui.text.brand': '#6c6fc8',
  'ui.interactive.hover': '#e3e4eb',
  'ui.interactive.disabled': '#e3e4eb',
  'ui.accent.brand.default': '#6c6fc8',
  'ui.accent.brand.hover': '#5055ab',
  'ui.accent.brand.active': '#3a408c',
  'ui.accent.brand.subtle': '#e8e7fe',
  'ui.accent.info.default': '#667aff',
  'ui.accent.info.subtle': '#edf4ff',
  'ui.accent.danger.default': '#e0024e',
  'ui.accent.danger.hover': '#f23864',
  'ui.accent.danger.active': '#bb0440',
  'ui.accent.danger.subtle': '#fef2f4',
  'ui.accent.success.default': '#00714a',
  'ui.accent.success.subtle': '#effff6',
  'ui.border.default': '#e3e4eb',
  'ui.border.strong': '#d3d4dd',
  'ui.border.subtle': '#f3f4f9',
  'ui.border.brand': '#5055ab',
  'ui.border.danger': '#e0024e',
  'ui.shadow.default': '#09090c',
  'ui.control.scrollbar.default': '#e3e4eb',
  'ui.control.scrollbar.hover': '#d3d4dd',
  'ui.decoration.grid.default': '#f3f4f9',
  'ui.decoration.grid.subtle': '#f9fafd',
  'ui.decoration.grid.brand': '#e8e7fe',
  'ui.decoration.grid.brand.subtle': '#f5f4ff',
  'ui.callout.info': '#3b82f6',
  'ui.callout.success': '#22c55e',
  'ui.callout.warning': '#f97316',
  'ui.callout.danger': '#dc2626',
  'ui.blockquote.message-sent': '#248bf5',
  'ui.blockquote.message-received': '#e5e5ea',
  'text.bright': '#ffffff',
  'text.black': '#17181c',
  'text.darkgray': '#525254',
  'text.gray': '#8c8c8d',
  'text.lightgray': '#c5c5c6',
  'text.white': '#ffffff',
  'text.red': '#ef4444',
  'text.orange': '#f97316',
  'text.amber': '#f59e0b',
  'text.yellow': '#eab308',
  'text.lime': '#84cc16',
  'text.green': '#22c55e',
  'text.emerald': '#10b981',
  'text.teal': '#14b8a6',
  'text.cyan': '#06b6d4',
  'text.sky': '#0ea5e9',
  'text.blue': '#3b82f6',
  'text.indigo': '#6366f1',
  'text.violet': '#8b5cf6',
  'text.purple': '#a855f7',
  'text.fuchsia': '#d946ef',
  'text.pink': '#ec4899',
  'text.rose': '#f43f5e',
  'bg.gray': '#f1f1f2',
  'bg.red': '#fdebec',
  'bg.orange': '#ffecd5',
  'bg.yellow': '#fef3c7',
  'bg.green': '#dff3e3',
  'bg.blue': '#e7f3f8',
  'bg.purple': '#f0e7fe',
  selection: '#99ccff',
};

export const DEFAULT_THEME: Theme = {
  colors: new Map(Object.entries(COLORS).map(([key, value]) => [key, colorToU32(value)])),
};
