name = "typie-eval"
main = ".svelte-kit/cloudflare/_worker.js"
compatibility_date = "2026-07-01"
compatibility_flags = ["nodejs_als"]
workers_dev = false

routes = [{ pattern = "eval.penxle.io", custom_domain = true }]

[vars]
INTERNAL_API_BASE = "https://api.typie.co"
PRISM_API_ORIGIN = "https://prism-api.penxle.io"

[assets]
binding = "ASSETS"
directory = ".svelte-kit/cloudflare"

[observability.logs]
enabled = true
invocation_logs = true

[[d1_databases]]
binding = "DB"
database_name = "typie-eval-beta"
database_id = "80e31c0b-81c4-487c-afb2-c66763c7cfc4"
migrations_dir = "migrations"
