workspace_dir := justfile_directory() / "../.."
target_dir := workspace_dir / "target"
mobile_dir := workspace_dir / "apps/mobile"
generated_dir := mobile_dir / "generated/uniffi"

crate := "editor_ffi"
mode := "release"
profile := if mode == "debug" { "dev" } else { "release" }

host_target := `rustc --print host-tuple`
cdylib_ext := if os() == "macos" { "dylib" } else { "so" }
bindgen := "cargo run --quiet -p editor-bindgen --features bin --bin"
host_bindgen_lib := target_dir / host_target / "debug" / "lib" + crate + "." + cdylib_ext

[private]
default:
    @just --list

# Build all platforms
all: desktop android ios wasm

# Build Android + iOS
mobile: android ios

# Build Desktop
desktop: host bindings-kotlin
    just icu-datagen {{target_dir}}/{{host_target}}/{{profile}}-uniffi/lib{{crate}}.{{cdylib_ext}} {{mobile_dir}}/compose/src/desktopMain/resources/icu.zst

# Build Android
android: bindings-kotlin (ensure "cargo-ndk")
    rustup target add aarch64-linux-android armv7-linux-androideabi x86_64-linux-android
    cargo ndk \
        -t arm64-v8a -t armeabi-v7a -t x86_64 \
        -o {{mobile_dir}}/android/src/main/jniLibs \
        build --manifest-path {{justfile_directory()}}/Cargo.toml \
        --profile {{profile}}-uniffi --features uniffi
    just icu-datagen {{mobile_dir}}/android/src/main/jniLibs/arm64-v8a/lib{{crate}}.so {{mobile_dir}}/android/src/main/assets/icu.zst

# Build iOS
ios: bindings-swift bindings-kotlin (build "uniffi" "aarch64-apple-ios") (build "uniffi" "aarch64-apple-ios-sim")
    #!/usr/bin/env bash
    set -e
    headers=$(mktemp -d)
    {{bindgen}} uniffi-bindgen-swift -- {{host_bindgen_lib}} \
        "$headers" --headers --modulemap --modulemap-filename module.modulemap --module-name EditorFFI
    mkdir -p {{mobile_dir}}/ios/Frameworks
    rm -rf {{mobile_dir}}/ios/Frameworks/Editor.xcframework
    xcodebuild -create-xcframework \
        -library {{target_dir}}/aarch64-apple-ios/{{profile}}-uniffi/lib{{crate}}.a -headers "$headers" \
        -library {{target_dir}}/aarch64-apple-ios-sim/{{profile}}-uniffi/lib{{crate}}.a -headers "$headers" \
        -output {{mobile_dir}}/ios/Frameworks/Editor.xcframework
    rm -rf "$headers"
    just icu-datagen {{target_dir}}/aarch64-apple-ios/{{profile}}-uniffi/lib{{crate}}.dylib {{mobile_dir}}/ios/Resources/icu.zst

# Build client + server WASM
wasm: wasm-browser wasm-server

# Build client WASM (browser)
wasm-browser: (ensure "wasm-opt")
    #!/usr/bin/env bash
    set -e
    rustup target add wasm32-unknown-unknown
    cargo build --manifest-path {{justfile_directory()}}/Cargo.toml \
        --profile {{profile}}-wasm --features wasm-browser --target wasm32-unknown-unknown
    {{bindgen}} wasm-bindgen-cli -- --target module --out-dir {{justfile_directory()}}/pkg/browser \
        {{target_dir}}/wasm32-unknown-unknown/{{profile}}-wasm/{{crate}}.wasm
    {{bindgen}} editor-bindgen-js -- {{justfile_directory()}}/pkg/browser/{{crate}}
    if [ "{{mode}}" = "release" ]; then
        wasm-opt -Os --all-features -o {{justfile_directory()}}/pkg/browser/{{crate}}_bg.wasm \
            {{justfile_directory()}}/pkg/browser/{{crate}}_bg.wasm
    fi
    just icu-datagen {{justfile_directory()}}/pkg/browser/{{crate}}_bg.wasm {{justfile_directory()}}/pkg/browser/icu.zst

# Build server WASM (Node.js)
wasm-server: (ensure "wasm-opt")
    #!/usr/bin/env bash
    set -e
    rustup target add wasm32-unknown-unknown
    cargo build --manifest-path {{justfile_directory()}}/Cargo.toml \
        --profile {{profile}}-wasm --features wasm-server --target wasm32-unknown-unknown
    {{bindgen}} wasm-bindgen-cli -- --target module --out-dir {{justfile_directory()}}/pkg/server \
        {{target_dir}}/wasm32-unknown-unknown/{{profile}}-wasm/{{crate}}.wasm
    {{bindgen}} editor-bindgen-js -- {{justfile_directory()}}/pkg/server/{{crate}}
    if [ "{{mode}}" = "release" ]; then
        wasm-opt -Os --all-features -o {{justfile_directory()}}/pkg/server/{{crate}}_bg.wasm \
            {{justfile_directory()}}/pkg/server/{{crate}}_bg.wasm
    fi
    just icu-datagen {{justfile_directory()}}/pkg/server/{{crate}}_bg.wasm {{justfile_directory()}}/pkg/server/icu.zst

[private]
ensure cmd *install:
    #!/usr/bin/env bash
    command -v {{cmd}} &> /dev/null || cargo install {{ if install == "" { cmd } else { install } }}

[private]
build features target:
    rustup target add {{target}}
    cargo build --manifest-path {{justfile_directory()}}/Cargo.toml \
        --profile {{profile}}-{{features}} --features {{features}} --target {{target}}

[private]
icu-datagen binary output: (ensure "icu4x-datagen")
    mkdir -p "$(dirname "{{output}}")"
    RUST_LOG=off icu4x-datagen --markers-for-bin "{{binary}}" --format blob | zstd -19 -f -o "{{output}}"

[private]
bindings-kotlin: host-bindgen
    rm -rf {{generated_dir}}/kotlin
    mkdir -p {{generated_dir}}/kotlin
    {{bindgen}} uniffi-bindgen -- generate \
        --library {{host_bindgen_lib}} \
        --language kotlin --out-dir {{generated_dir}}/kotlin/ --no-format
    rm -rf {{mobile_dir}}/compose/build/generated/editor-bindgen
    {{bindgen}} editor-bindgen-kotlin -- \
        {{host_bindgen_lib}} \
        --base-dir {{mobile_dir}}/compose/build/generated/editor-bindgen

[private]
bindings-swift: host-bindgen
    rm -rf {{generated_dir}}/swift
    mkdir -p {{generated_dir}}/swift
    {{bindgen}} uniffi-bindgen-swift -- {{host_bindgen_lib}} \
        {{generated_dir}}/swift --swift-sources
    {{bindgen}} editor-bindgen-swift -- \
        {{host_bindgen_lib}} \
        {{mobile_dir}}/generated/editor-bindgen/swift

[private]
host: (build "uniffi" host_target)

[private]
host-bindgen:
    cargo build --manifest-path {{justfile_directory()}}/Cargo.toml \
        --features uniffi --target {{host_target}}
