[package]
name = "prism-ui-renderer"
version.workspace = true
edition.workspace = true
build = "build.rs"

[dependencies]
bytemuck.workspace = true
glam.workspace = true
thiserror.workspace = true
wgpu.workspace = true
workspace-hack = { version = "0.1", path = "../workspace-hack" }

[build-dependencies]
naga.workspace = true
