targets:
  $default:
    builders:
      ferry_generator|graphql_builder:
        enabled: true
        options:
          schema: typie|lib/graphql/schema.graphql
          when_extensions:
            when: true
            maybeWhen: true
          tristate_optionals: true
          type_overrides:
            DateTime:
              name: Jiffy
              import: 'package:jiffy/jiffy.dart'
            JSON:
              name: JsonObject
              import: 'package:built_value/json_object.dart'
      ferry_generator|serializer_builder:
        enabled: true
        options:
          schema: typie|lib/graphql/schema.graphql
          type_overrides:
            DateTime:
              name: Jiffy
              import: 'package:jiffy/jiffy.dart'
            JSON:
              name: JsonObject
              import: 'package:built_value/json_object.dart'
          custom_serializers:
            - import: 'package:typie/graphql/serializer.dart'
              name: DateTimeSerializer
            - import: 'package:built_value/src/json_object_serializer.dart'
              name: JsonObjectSerializer
