[package]
name = "prism-ui-web"
edition = "2024"
license = "MIT OR Apache-2.0"
rust-version = "1.87"
version = "0.1.0"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
bytemuck.workspace = true
js-sys.workspace = true
prism-ui-renderer.workspace = true
wasm-bindgen.workspace = true
wasm-bindgen-futures.workspace = true
wgpu.workspace = true
workspace-hack = { version = "0.1", path = "../workspace-hack" }

[dependencies.web-sys]
workspace = true
features = [
  "HtmlCanvasElement",
]
