default:
    @just --list

build:
    @cargo build
    @codesign --entitlements entitlements.plist -s - ../../target/debug/vermuda

release:
    @cargo build --release
    @codesign --entitlements entitlements.plist -s - ../../target/release/vermuda

run *args: build
    @VM_HOME={{justfile_directory()}} ../../target/debug/vermuda {{args}}

run-release *args: release
    @VM_HOME={{justfile_directory()}} ../../target/release/vermuda {{args}}

clean:
    @cargo clean
