[package]
name = "workspace-hack"
version = "0.1.0"
edition = "2024"
description = "workspace-hack package, managed by hakari"
publish = false

### BEGIN HAKARI SECTION
[dependencies]
bytemuck = { version = "1", default-features = false, features = ["derive", "extern_crate_alloc", "min_const_generics", "must_cast"] }
hashbrown = { version = "0.17" }
icu_locale_core = { version = "2", default-features = false, features = ["alloc", "serde", "zerovec"] }
icu_provider = { version = "2", default-features = false, features = ["alloc", "baked", "deserialize_postcard_1", "sync"] }
icu_segmenter = { version = "2", default-features = false, features = ["auto", "compiled_data", "serde"] }
imbl = { version = "7", default-features = false, features = ["serde"] }
indexmap = { version = "2" }
js-sys = { version = "0.3" }
litemap = { version = "0.8", default-features = false, features = ["serde"] }
log = { version = "0.4", default-features = false, features = ["std"] }
naga-types = { version = "30", default-features = false, features = ["std"] }
once_cell = { version = "1", default-features = false, features = ["alloc"] }
phf_shared = { version = "0.14", default-features = false, features = ["std"] }
read-fonts = { version = "0.42" }
serde = { version = "1", features = ["alloc", "derive"] }
serde_core = { version = "1", features = ["alloc"] }
serde_json = { version = "1", features = ["unbounded_depth"] }
smallvec = { version = "1", default-features = false, features = ["const_new", "serde"] }
stable_deref_trait = { version = "1" }
thiserror = { version = "2" }
tinystr = { version = "0.8", default-features = false, features = ["alloc", "serde", "zerovec"] }
uncased = { version = "0.9" }
wasm-bindgen = { version = "0.2" }
web-sys = { version = "0.3", features = ["CanvasRenderingContext2d", "Document", "Event", "History", "HtmlCanvasElement", "HtmlHeadElement", "ImageData", "Location", "OffscreenCanvas", "WebGl2RenderingContext", "WebGlFramebuffer", "WebGlTexture", "Window", "console"] }
zerotrie = { version = "0.2", default-features = false, features = ["serde", "yoke", "zerofrom", "zerovec"] }

[build-dependencies]
bytemuck = { version = "1", default-features = false, features = ["derive", "extern_crate_alloc", "min_const_generics", "must_cast"] }
hashbrown = { version = "0.17" }
icu_locale_core = { version = "2", default-features = false, features = ["alloc", "serde", "zerovec"] }
icu_provider = { version = "2", default-features = false, features = ["alloc", "baked", "deserialize_postcard_1", "sync"] }
icu_segmenter = { version = "2", default-features = false, features = ["auto", "compiled_data", "serde"] }
imbl = { version = "7", default-features = false, features = ["serde"] }
indexmap = { version = "2" }
js-sys = { version = "0.3" }
litemap = { version = "0.8", default-features = false, features = ["serde"] }
log = { version = "0.4", default-features = false, features = ["std"] }
naga-types = { version = "30", default-features = false, features = ["std"] }
once_cell = { version = "1", default-features = false, features = ["alloc"] }
phf_shared = { version = "0.14", default-features = false, features = ["std"] }
read-fonts = { version = "0.42" }
serde = { version = "1", features = ["alloc", "derive"] }
serde_core = { version = "1", features = ["alloc"] }
serde_json = { version = "1", features = ["unbounded_depth"] }
smallvec = { version = "1", default-features = false, features = ["const_new", "serde"] }
stable_deref_trait = { version = "1" }
syn-7b89eefb6aaa9bf3 = { package = "syn", version = "3", features = ["extra-traits", "full", "visit-mut"] }
syn-f595c2ba2a3f28df = { package = "syn", version = "2", features = ["extra-traits", "fold", "full", "visit", "visit-mut"] }
thiserror = { version = "2" }
tinystr = { version = "0.8", default-features = false, features = ["alloc", "serde", "zerovec"] }
uncased = { version = "0.9" }
wasm-bindgen = { version = "0.2" }
web-sys = { version = "0.3", features = ["CanvasRenderingContext2d", "Document", "Event", "History", "HtmlCanvasElement", "HtmlHeadElement", "ImageData", "Location", "OffscreenCanvas", "WebGl2RenderingContext", "WebGlFramebuffer", "WebGlTexture", "Window", "console"] }
zerotrie = { version = "0.2", default-features = false, features = ["serde", "yoke", "zerofrom", "zerovec"] }

[target.aarch64-apple-darwin.dependencies]
bitflags = { version = "2", default-features = false, features = ["std"] }
block2 = { version = "0.6" }
libc = { version = "0.2" }
naga = { version = "30", features = ["glsl-in", "msl-out", "wgsl-in", "wgsl-out"] }
objc2 = { version = "0.6" }
objc2-core-foundation = { version = "0.3" }
objc2-foundation = { version = "0.3", default-features = false, features = ["NSArray", "NSBundle", "NSData", "NSDictionary", "NSEnumerator", "NSError", "NSGeometry", "NSKeyValueObserving", "NSNotification", "NSNull", "NSObjCRuntime", "NSObject", "NSProcessInfo", "NSRange", "NSString", "NSThread", "NSURL", "NSValue", "objc2-core-foundation", "std"] }
objc2-metal = { version = "0.3" }
once_cell = { version = "1", default-features = false, features = ["std"] }
smallvec = { version = "1", default-features = false, features = ["union"] }

[target.aarch64-apple-darwin.build-dependencies]
bitflags = { version = "2", default-features = false, features = ["std"] }
block2 = { version = "0.6" }
libc = { version = "0.2" }
naga = { version = "30", features = ["glsl-in", "msl-out", "wgsl-in", "wgsl-out"] }
objc2 = { version = "0.6" }
objc2-core-foundation = { version = "0.3" }
objc2-foundation = { version = "0.3", default-features = false, features = ["NSArray", "NSBundle", "NSData", "NSDictionary", "NSEnumerator", "NSError", "NSGeometry", "NSKeyValueObserving", "NSNotification", "NSNull", "NSObjCRuntime", "NSObject", "NSProcessInfo", "NSRange", "NSString", "NSThread", "NSURL", "NSValue", "objc2-core-foundation", "std"] }
objc2-metal = { version = "0.3" }
once_cell = { version = "1", default-features = false, features = ["std"] }
smallvec = { version = "1", default-features = false, features = ["union"] }

[target.wasm32-unknown-unknown.dependencies]
wasm-bindgen-futures = { version = "0.4" }
web-sys = { version = "0.3", default-features = false, features = ["HtmlImageElement", "HtmlVideoElement", "ImageBitmap", "MediaQueryList", "Navigator", "NodeList", "VideoFrame", "WorkerGlobalScope", "WorkerNavigator"] }

[target.wasm32-unknown-unknown.build-dependencies]
wasm-bindgen-futures = { version = "0.4" }
web-sys = { version = "0.3", default-features = false, features = ["HtmlImageElement", "HtmlVideoElement", "ImageBitmap", "MediaQueryList", "Navigator", "NodeList", "VideoFrame", "WorkerGlobalScope", "WorkerNavigator"] }

### END HAKARI SECTION
