machine:
  install:
    disk: /dev/vda
    image: factory.talos.dev/metal-installer/00d2f5d6e5b7b42bedaf6b6b2a400aa7dcc5d00aafa19236337e3d3b7982695a:v1.12.4

  kubelet:
    extraConfig:
      imageGCHighThresholdPercent: 60
      imageGCLowThresholdPercent: 50

  features:
    hostDNS:
      forwardKubeDNSToHost: false
      resolveMemberNames: true

cluster:
  network:
    cni:
      name: none
    podSubnets:
      - 10.10.0.0/16
    serviceSubnets:
      - 10.20.0.0/16

  apiServer:
    extraArgs:
      enable-aggregator-routing: 'true'
      oidc-issuer-url: https://dex.typie.io
      oidc-client-id: kubernetes
      oidc-username-claim: email
      oidc-groups-claim: groups

    admissionControl:
      - name: PodSecurity
        configuration:
          defaults:
            audit: privileged
            enforce: privileged
            warn: privileged

  controllerManager:
    extraArgs:
      bind-address: 0.0.0.0

  scheduler:
    extraArgs:
      bind-address: 0.0.0.0

  proxy:
    disabled: true
---
apiVersion: v1alpha1
kind: DHCPv4Config
name: enp0s1
---
apiVersion: v1alpha1
kind: ResolverConfig
nameservers:
  - address: 1.1.1.1
  - address: 1.0.0.1
