[package]
name = "fondue"
version.workspace = true
edition.workspace = true

[lib]
crate-type = ["cdylib"]

[dependencies]
cxx = "*"
napi = "*"
napi-derive = "*"
ttf-parser = "*"

[build-dependencies]
cc = "*"
cxx-build = "*"
glob = "*"
napi-build = "*"
