export const IPC = {
  tabsState: 'tabs:state',
  tabsNew: 'tabs:new',
  tabsClose: 'tabs:close',
  tabsActivate: 'tabs:activate',
  tabsMove: 'tabs:move',
  tabsRequestClose: 'tabs:request-close',
  tabIcon: 'tab:icon',
  tabOpen: 'tab:open',
  theme: 'theme',
  themeChanged: 'theme:changed',
  menuPopup: 'menu:popup',
  authLogin: 'auth:login',
  authCancel: 'auth:cancel',
  authError: 'auth:error',
  pageRetry: 'page:retry',
  contextMenu: 'contextmenu:request',
  bridgeOpenExternal: 'bridge:open-external',
  bridgeFocus: 'bridge:focus',
  bridgePreference: 'bridge:preference',
  bridgeZoom: 'bridge:zoom',
  bridgeZoomShortcut: 'bridge:zoom-shortcut',
  updateReady: 'update:ready',
  updateRestart: 'update:restart',
  windowFullscreen: 'window:fullscreen',
} as const;
