export const IPC = {
  tabsState: 'tabs:state',
  tabsNew: 'tabs:new',
  tabsClose: 'tabs:close',
  tabsActivate: 'tabs:activate',
  tabsMove: 'tabs:move',
  theme: 'theme',
  themeChanged: 'theme:changed',
  menuPopup: 'menu:popup',
  authLogin: 'auth:login',
  authCancel: 'auth:cancel',
  authError: 'auth:error',
  pageRetry: 'page:retry',
  contextMenu: 'contextmenu:request',
  bridgeOpenExternal: 'bridge:open-external',
  bridgeFocus: 'bridge:focus',
  updateReady: 'update:ready',
  updateRestart: 'update:restart',
  updateDismiss: 'update:dismiss',
} as const;
