import * as E from '@typie/lib/enums';
import { pgEnum } from 'drizzle-orm/pg-core';

function createPgEnum<T extends string>(enumName: string, obj: Record<string, T>) {
  return pgEnum(enumName, Object.values(obj) as [T, ...T[]]);
}

export const _BillingKeyType = createPgEnum('_billing_key_type', E.BillingKeyType);
export const _CouponState = createPgEnum('_coupon_state', E.CouponState);
export const _CreditCodeState = createPgEnum('_credit_code_state', E.CreditCodeState);
export const _EntityAvailability = createPgEnum('_entity_availability', E.EntityAvailability);
export const _EntityState = createPgEnum('_entity_state', E.EntityState);
export const _EntityType = createPgEnum('_entity_type', E.EntityType);
export const _EntityVisibility = createPgEnum('_entity_visibility', E.EntityVisibility);
export const _FontState = createPgEnum('_font_state', E.FontState);
export const _FontFamilyState = createPgEnum('_font_family_state', E.FontFamilyState);
export const _InAppPurchaseRecordState = createPgEnum('_in_app_purchase_record_state', E.InAppPurchaseRecordState);
export const _InAppPurchaseStore = createPgEnum('_in_app_purchase_store', E.InAppPurchaseStore);
export const _NoteStatus = createPgEnum('_note_status', E.NoteStatus);
export const _NoteState = createPgEnum('_note_state', E.NoteState);
export const _PaymentInvoiceState = createPgEnum('_payment_invoice_state', E.PaymentInvoiceState);
export const _PaymentOutcome = createPgEnum('_payment_outcome', E.PaymentOutcome);
export const _PlanAvailability = createPgEnum('_plan_availability', E.PlanAvailability);
export const _PlanInterval = createPgEnum('_plan_interval', E.PlanInterval);
export const _DocumentContentRating = createPgEnum('_document_content_rating', E.DocumentContentRating);
export const _DocumentCommentThreadState = createPgEnum('_document_comment_thread_state', E.DocumentCommentThreadState);
export const _DocumentCommentState = createPgEnum('_document_comment_state', E.DocumentCommentState);
export const _DocumentType = createPgEnum('_document_type', E.DocumentType);
export const _DocumentConflictKind = createPgEnum('_document_conflict_kind', E.DocumentConflictKind);
export const _DocumentBundleKind = createPgEnum('_document_bundle_kind', E.DocumentBundleKind);
export const _DocumentHeadKind = createPgEnum('_document_head_kind', E.DocumentHeadKind);
export const _PreorderPaymentState = createPgEnum('_preorder_payment_state', E.PreorderPaymentState);
export const _PrismWorkflowState = createPgEnum('_prism_workflow_state', E.PrismWorkflowState);
export const _PrismReviewTier = createPgEnum('_prism_review_tier', E.PrismReviewTier);
export const _PrismReaction = createPgEnum('_prism_reaction', E.PrismReaction);
export const _PrismReviewPass = createPgEnum('_prism_review_pass', E.PrismReviewPass);
export const _PrismReviewThreadState = createPgEnum('_prism_review_thread_state', E.PrismReviewThreadState);
export const _PrismReviewCommentAuthor = createPgEnum('_prism_review_comment_author', E.PrismReviewCommentAuthor);
export const _RedirectType = createPgEnum('_redirect_type', E.RedirectType);
export const _SiteDateDisplay = createPgEnum('_site_date_display', E.SiteDateDisplay);
export const _SiteState = createPgEnum('_site_state', E.SiteState);
export const _SingleSignOnProvider = createPgEnum('_single_sign_on_provider', E.SingleSignOnProvider);
export const _SubscriptionState = createPgEnum('_subscription_state', E.SubscriptionState);
export const _TextReplacementState = createPgEnum('_text_replacement_state', E.TextReplacementState);
export const _UserDevicePlatform = createPgEnum('_user_device_platform', E.UserDevicePlatform);
export const _UserRole = createPgEnum('_user_role', E.UserRole);
export const _UserState = createPgEnum('_user_state', E.UserState);
export const _LlmAnalysisRunState = createPgEnum('_llm_analysis_run_state', E.LlmAnalysisRunState);
export const _LlmCallState = createPgEnum('_llm_call_state', E.LlmCallState);
