package co.typie.domain.subscription

enum class GatedAction {
  CreateDocument,
  CreateFolder,
  CreateSpace,
  CreateNote,
  EditNote,
  RenameEntity,
  ChangeIcon,
  DuplicateDocument,
  ExportDocument,
  ConvertDocumentType,
  MoveEntity,
  Paste,
  RecoverFromTrash,
  UpdateSpace,
  ChangeSpaceAddress,
  ShareFolder,
  ShareDocument,
  UploadFont,
  TextReplacement,
  PresetSettings,
  AiSettings,
  Comment,
  Spellcheck,
  AiFeedback,
  Generic,
}
