default_platform(:ios)

platform :ios do
  desc "Set up signing credentials"
  lane :setup do
    app_store_connect_api_key

    match(type: "development")
    match(type: "appstore")
  end

  desc "Build and upload to beta"
  lane :beta do
    app_store_connect_api_key

    match(type: "appstore", readonly: true)

    latest_build_number = latest_testflight_build_number

    build_app(
      project: "App.xcodeproj",
      scheme: "iOS",
      configuration: "Release",
      export_method: "app-store",
      output_directory: "build",
      xcargs: "CURRENT_PROJECT_VERSION=#{latest_build_number + 1}",
    )

    if ENV["SENTRY_AUTH_TOKEN"]
      sentry_debug_files_upload(
        org_slug: "typie",
        project_slug: "app2",
        path: lane_context[SharedValues::DSYM_OUTPUT_PATH],
      )
    else
      UI.important("SENTRY_AUTH_TOKEN is not set; skipping Sentry dSYM upload")
    end

    upload_to_testflight(
      notify_external_testers: false,
    )
  end
end
