/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const __wbg_editorhost_free: (a: number, b: number) => void;
export const editorhost_create: (a: any) => any;
export const editorhost_create_editor: (a: number, b: number, c: number, d: any) => [number, number, number];
export const editorhost_load_font_base: (a: number, b: number, c: number, d: number, e: number, f: number) => [number, number];
export const editorhost_load_font_chunk: (a: number, b: number, c: number, d: number, e: number, f: number) => [number, number];
export const editorhost_load_icu_data: (a: number, b: number, c: number) => [number, number];
export const editorhost_set_fallback_font_families: (a: number, b: number, c: number) => [number, number];
export const __wbg_editor_free: (a: number, b: number) => void;
export const editor_attach_surface: (a: number, b: number, c: any, d: number, e: number, f: number) => [number, number];
export const editor_detach_surface: (a: number, b: number) => [number, number];
export const editor_enqueue: (a: number, b: any) => [number, number];
export const editor_render_surface: (a: number, b: number) => [number, number];
export const editor_resize_surface: (a: number, b: number, c: number, d: number, e: number) => [number, number];
export const editor_selection: (a: number) => [number, number, number];
export const editor_tick: (a: number) => [number, number, number, number];
export const wasm_bindgen_9a220f7c351cea56___convert__closures_____invoke___wasm_bindgen_9a220f7c351cea56___JsValue__core_260d1872709b9755___result__Result_____wasm_bindgen_9a220f7c351cea56___JsError___true_: (a: number, b: number, c: any) => [number, number];
export const wasm_bindgen_9a220f7c351cea56___convert__closures_____invoke___js_sys_442aac94dfdb7dbd___Function_fn_wasm_bindgen_9a220f7c351cea56___JsValue_____wasm_bindgen_9a220f7c351cea56___sys__Undefined___js_sys_442aac94dfdb7dbd___Function_fn_wasm_bindgen_9a220f7c351cea56___JsValue_____wasm_bindgen_9a220f7c351cea56___sys__Undefined_______true_: (a: number, b: number, c: any, d: any) => void;
export const wasm_bindgen_9a220f7c351cea56___convert__closures_____invoke___wasm_bindgen_9a220f7c351cea56___JsValue______true_: (a: number, b: number, c: any) => void;
export const wasm_bindgen_9a220f7c351cea56___convert__closures_____invoke___wgpu_b2797b22d22173fd___backend__webgpu__webgpu_sys__gen_GpuUncapturedErrorEvent__GpuUncapturedErrorEvent______true_: (a: number, b: number, c: any) => void;
export const wasm_bindgen_9a220f7c351cea56___convert__closures_____invoke___bool__true_: (a: number, b: number) => number;
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __wbindgen_realloc: (a: number, b: number, c: number, d: number) => number;
export const __wbindgen_exn_store: (a: number) => void;
export const __externref_table_alloc: () => number;
export const __wbindgen_externrefs: WebAssembly.Table;
export const __wbindgen_free: (a: number, b: number, c: number) => void;
export const __wbindgen_destroy_closure: (a: number, b: number) => void;
export const __externref_table_dealloc: (a: number) => void;
export const __externref_drop_slice: (a: number, b: number) => void;
export const __wbindgen_start: () => void;
