name: Build

on:
  workflow_call:
    inputs:
      app:
        required: true
        type: string
        description: The app to build.
    outputs:
      sha:
        value: ${{ jobs.build.outputs.sha }}
        description: Short SHA of the built commit.

permissions:
  contents: read
  id-token: write

jobs:
  build:
    name: Build
    runs-on: arc-p-8x

    outputs:
      sha: ${{ steps.sha.outputs.sha }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 26
          cache: 'pnpm'

      - name: Run turbo prune
        run: pnpm dlx turbo prune @typie/${{ inputs.app }} --docker

      - name: Download WASM artifact
        uses: actions/download-artifact@v8
        with:
          name: editor-wasm
          path: out/full/crates/editor-ffi/pkg/

      - name: Download Prism UI WASM artifact
        if: inputs.app == 'website'
        uses: actions/download-artifact@v8
        with:
          name: prism-ui-wasm
          path: out/full/crates/prism-ui-web/pkg/

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::509399603331:role/actions@github
          aws-region: ap-northeast-2

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Compute short SHA
        id: sha
        run: echo "sha=${GITHUB_SHA:0:7}" >> $GITHUB_OUTPUT

      - name: Generate ECR metadata
        id: meta-ecr
        uses: docker/metadata-action@v6
        with:
          images: 509399603331.dkr.ecr.ap-northeast-2.amazonaws.com/${{ inputs.app }}
          flavor: latest=false
          tags: |
            type=sha,prefix=dev-,priority=300
            type=raw,value=dev-latest

      - name: Build image
        uses: docker/build-push-action@v7
        with:
          push: true
          context: .
          file: apps/${{ inputs.app }}/Dockerfile
          tags: ${{ steps.meta-ecr.outputs.tags }}
          labels: ${{ steps.meta-ecr.outputs.labels }}
          build-args: |
            IMAGE_TAG=${{ steps.sha.outputs.sha }}
          secrets: |
            TURBO_TOKEN=${{ secrets.TURBO_TOKEN }}
          cache-from: type=registry,ref=509399603331.dkr.ecr.ap-northeast-2.amazonaws.com/cache:${{ inputs.app }}
          cache-to: type=registry,ref=509399603331.dkr.ecr.ap-northeast-2.amazonaws.com/cache:${{ inputs.app }},mode=max,compression=zstd,image-manifest=true,oci-mediatypes=true,ignore-error=true
