name: CD

on:
  push:
    branches:
      - main

concurrency:
  group: cd-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  packages: write

jobs:
  build-wasm:
    name: Build (wasm)
    uses: ./.github/workflows/build-wasm.yml

  build-wasm-legacy:
    name: Build (legay wasm)
    uses: ./.github/workflows/build-wasm-legacy.yml

  build-api:
    name: Build (api)
    needs: [build-wasm, build-wasm-legacy]
    uses: ./.github/workflows/build.yml
    with:
      app: api
    secrets: inherit

  build-website:
    name: Build (website)
    needs: [build-wasm, build-wasm-legacy]
    uses: ./.github/workflows/build.yml
    with:
      app: website
    secrets: inherit

  deploy-dev:
    name: Deployment (dev)
    needs: [build-api, build-website]
    uses: ./.github/workflows/deployment.yml
    with:
      stack: dev
      version: ${{ needs.build-api.outputs.version }}
    secrets: inherit
