name: CI

on:
  push:
    branches: [main]
  pull_request:
  merge_group:

permissions:
  contents: read
  packages: read

env:
  TURBO_TEAM: penxle
  TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
  TURBO_REMOTE_ONLY: true

jobs:
  lint:
    name: Lint
    runs-on: linux-x64-16vcpu
    strategy:
      fail-fast: false
      matrix:
        linter: [eslint, prettier, spellcheck, svelte, syncpack, typecheck]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Bun
        uses: oven-sh/setup-bun@v2

      - name: Install dependencies
        run: bun install --frozen-lockfile
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Run lint
        run: bun run lint:${{ matrix.linter }}
